// Auto-generated by scripts/convert-commercial.mjs
export const COMMERCIAL_OFFICE_PAGE_META = {
  "commercial_pest_control": {
    "title": "Commercial Pest Control - 7 States Pest Control",
    "description": "Professional commercial pest control in Melbourne for offices, restaurants, schools, warehouses and factories. Customised pest management solutions for your business.",
    "bodyClass": "wp-singular page-template page-template-elementor_header_footer page wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-694"
  },
  "office_pest_control": {
    "title": "Professional Office Pest Control Services | office pest control",
    "description": "Get reliable office pest control service to keep your workspace pest-free. We offer expert office building pest control and office of pest management solutions.",
    "bodyClass": "wp-singular page-template page-template-elementor_header_footer page wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-697"
  },
  "restaurant_cafe_pest_control": {
    "title": "Restaurant Pest Control Services in Melbourne | 7 States Pest Control",
    "description": "Looking for reliable restaurant pest control in Melbourne? 7 States Pest Control offers eco-friendly, effective solutions for restaurants and cafes, ensuring compliance with health codes and keeping your establishment pest-free. Contact us today for a free quote!",
    "bodyClass": "wp-singular page-template page-template-elementor_header_footer page wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-700"
  },
  "school_and_hospitality_facility_pest_control": {
    "title": "Effective Pest Control for Schools & Hospitals | pest control hospital",
    "description": "Professional school pest control in Melbourne & hospital pest control services. Ensure a safe environment with expert education facility pest control Melbourne.",
    "bodyClass": "wp-singular page-template page-template-elementor_header_footer page wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-702"
  },
  "warehouse_and_factory_pest_control_services_melbourne": {
    "title": "Effective Pest Control for Warehouse & Factories in Melbourne",
    "description": "Professional warehouse pest management services in Melbourne. Trusted warehouse pest control company for food warehouses & factories. Safe & reliable solutions.",
    "bodyClass": "wp-singular page-template page-template-elementor_header_footer page wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-704"
  },
  "melbourne": {
    "title": "Pest Control Melbourne | Safe & Affordable Pest Removal Services",
    "description": "Get expert pest control in Melbourne with 7 States Pest Control. We offer safe, eco-friendly, and affordable solutions for rodents, termites, possums, and more.",
    "bodyClass": "wp-singular page-template page-template-elementor_header_footer page wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-710"
  }
}
