// Auto-generated by scripts/scrape-and-convert-location.mjs
export const LOCATION_PAGE_META = {
  "location_archive": {
    "title": "Location Archive - 7 States Pest Control",
    "description": "",
    "bodyClass": "archive post-type-archive post-type-archive-location wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-page-9386 elementor-default elementor-template-full-width elementor-kit-9"
  },
  "location_altona": {
    "title": "Pest Control Altona- Expert Pest Removal Services.",
    "description": "Reliable pest control in Altona for wasps, rodents, spiders, and bed bugs. Safe, fast, and affordable treatments for homes and businesses. Book today!",
    "bodyClass": "wp-singular location-template-default single single-location postid-9751 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9751 elementor-page-9421"
  },
  "location_armadale": {
    "title": "Pest Control Armadale- Expert Pest Removal Services.",
    "description": "Reliable pest control in Armadale for wasps, rodents, spiders, and bed bugs. Safe, fast, and affordable treatments for homes and businesses. Book today!",
    "bodyClass": "wp-singular location-template-default single single-location postid-9759 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9759 elementor-page-9421"
  },
  "location_beaumaris": {
    "title": "Pest Control Beaumaris- Expert Pest Removal Services.",
    "description": "Reliable pest control in Beaumaris for wasps, rodents, spiders, and bed bugs. Safe, fast, and affordable treatments for homes and businesses. Book today!",
    "bodyClass": "wp-singular location-template-default single single-location postid-9697 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9697 elementor-page-9421"
  },
  "location_bentleigh": {
    "title": "Pest Control Bentleigh - Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Bentleigh? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-9687 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9687 elementor-page-9421"
  },
  "location_brighton": {
    "title": "Pest Control Brighton- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Brighton? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-9668 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9668 elementor-page-9421"
  },
  "location_brunswick": {
    "title": "Pest Control Brunswick- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Brunswick? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-9707 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9707 elementor-page-9421"
  },
  "location_carlton": {
    "title": "Pest Control Carlton- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Carlton? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-9711 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9711 elementor-page-9421"
  },
  "location_carnegie": {
    "title": "Pest Control Carnegie- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Carnegie? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-9693 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9693 elementor-page-9421"
  },
  "location_caufield": {
    "title": "Pest Control Caufield- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Caufield? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-9705 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9705 elementor-page-9421"
  },
  "location_cheltenham": {
    "title": "Pest Control Cheltenham- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Cheltenham? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-9691 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9691 elementor-page-9421"
  },
  "location_clayton": {
    "title": "Pest Control Clayton- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Clayton? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-9828 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9828 elementor-page-9421"
  },
  "location_coburg": {
    "title": "Pest Control Coburg- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Coburg? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-9838 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9838 elementor-page-9421"
  },
  "location_craigieburn": {
    "title": "Pest Control Craigieburn- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Craigieburn? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-9847 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9847 elementor-page-9421"
  },
  "location_cranbourne": {
    "title": "Pest Control Cranbourne- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Cranbourne? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-9854 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9854 elementor-page-9421"
  },
  "location_dandenong": {
    "title": "Pest Control Dandenong- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Dandenong? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-9868 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9868 elementor-page-9421"
  },
  "location_doreen": {
    "title": "Pest Control Doreen- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Doreen? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-9922 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9922 elementor-page-9421"
  },
  "location_elwood": {
    "title": "Pest Control Elwood- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Elwood ? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-9932 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9932 elementor-page-9421"
  },
  "location_ferntree_gully": {
    "title": "Pest Control Ferntree Gully- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Ferntree Gully? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-9938 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9938 elementor-page-9421"
  },
  "location_fitzroy": {
    "title": "Pest Control Fitzroy - Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Fitzroy ? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-9949 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9949 elementor-page-9421"
  },
  "location_flemington": {
    "title": "Pest Control Flemington- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Flemington ? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-9955 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9955 elementor-page-9421"
  },
  "location_footscray": {
    "title": "Pest Control Footscray- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Footscray ? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-9961 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9961 elementor-page-9421"
  },
  "location_frankston": {
    "title": "Pest Control Frankston- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Frankston ? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-9971 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9971 elementor-page-9421"
  },
  "location_glenroy": {
    "title": "Pest Control Glenroy- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Glenroy ? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-9978 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9978 elementor-page-9421"
  },
  "location_hampton": {
    "title": "Pest Control Hampton- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Hampton? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-9689 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9689 elementor-page-9421"
  },
  "location_highett": {
    "title": "Pest Control Highett- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Highett? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10003 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10003 elementor-page-9421"
  },
  "location_kalkallo": {
    "title": "Pest Control Kalkallo- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Kalkallo? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-9699 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-9699 elementor-page-9421"
  },
  "location_mandurah": {
    "title": "Pest Control Mandurah- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Mandurah? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10009 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10009 elementor-page-9421"
  },
  "location_melton": {
    "title": "Pest Control Melton- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Melton? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10016 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10016 elementor-page-9421"
  },
  "location_mernda": {
    "title": "Pest Control Mernda- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Mernda? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10023 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10023 elementor-page-9421"
  },
  "location_mornington": {
    "title": "Pest Control Mornington- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Mornington ? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10031 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10031 elementor-page-9421"
  },
  "location_mount_waverley": {
    "title": "Pest Control Mount Waverley- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Mount Waverley? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10038 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10038 elementor-page-9421"
  },
  "location_north_melbourne": {
    "title": "Pest Control North Melbourne- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in North Melbourne? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10044 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10044 elementor-page-9421"
  },
  "location_pakenham": {
    "title": "Pest Control Pakenham- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Pakenham? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10052 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10052 elementor-page-9421"
  },
  "location_point_cook": {
    "title": "Pest Control Point Cook- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Point Cook? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10058 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10058 elementor-page-9421"
  },
  "location_port_melbourne": {
    "title": "Pest Control Port Melbourne- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Port Melbourne? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10065 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10065 elementor-page-9421"
  },
  "location_richmond": {
    "title": "Pest Control Richmond- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Richmond? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10112 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10112 elementor-page-9421"
  },
  "location_ringwood": {
    "title": "Pest Control Ringwood- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Ringwood? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10124 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10124 elementor-page-9421"
  },
  "location_sandringham": {
    "title": "Pest Control Sandringham- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Sandringham? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10134 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10134 elementor-page-9421"
  },
  "location_seaford": {
    "title": "Pest Control Seaford- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Seaford? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10144 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10144 elementor-page-9421"
  },
  "location_south_melbourne": {
    "title": "Pest Control South Melbourne- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in South Melbourne? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10150 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10150 elementor-page-9421"
  },
  "location_south_morang": {
    "title": "Pest Control South Morang- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in South Morang? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10161 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10161 elementor-page-9421"
  },
  "location_south_yara": {
    "title": "Pest Control South Yara- Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in South Yara? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10167 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10167 elementor-page-9421"
  },
  "location_springvale": {
    "title": "Pest Control Springvale Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Springvale? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10174 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10174 elementor-page-9421"
  },
  "location_st_albans": {
    "title": "Pest Control St Albans Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in St Albans? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10185 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10185 elementor-page-9421"
  },
  "location_st_kilda": {
    "title": "Pest Control St Kilda Expert Pest Removal Services.",
    "description": "Looking for reliable pest control inSt Kilda? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10191 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10191 elementor-page-9421"
  },
  "location_sunshine": {
    "title": "Pest Control Sunshine Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Sunshine? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10198 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10198 elementor-page-9421"
  },
  "location_tarneit": {
    "title": "Pest Control Tarneit Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Tarneit? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10206 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10206 elementor-page-9421"
  },
  "location_taylors_lakes": {
    "title": "Pest Control Taylors Lakes Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Taylors Lakes? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10216 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10216 elementor-page-9421"
  },
  "location_thomastown": {
    "title": "Pest Control Thomastown Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Thomastown? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10223 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10223 elementor-page-9421"
  },
  "location_truganina": {
    "title": "Pest Control Truganina Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Truganina? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10231 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10231 elementor-page-9421"
  },
  "location_werribee": {
    "title": "Pest Control Werribee Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Werribee? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10242 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10242 elementor-page-9421"
  },
  "location_williamstown": {
    "title": "Pest Control Williamstown Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Williamstown? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10249 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10249 elementor-page-9421"
  },
  "location_wyndham_vale": {
    "title": "Pest Control Wyndham Vale Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Wyndham Vale? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10257 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10257 elementor-page-9421"
  },
  "location_yarraville": {
    "title": "Pest Control Yarraville Expert Pest Removal Services.",
    "description": "Looking for reliable pest control in Yarraville? Our expert team provides safe and effective pest removal services to protect your home or business.",
    "bodyClass": "wp-singular location-template-default single single-location postid-10264 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-kit-9 elementor-page elementor-page-10264 elementor-page-9421"
  }
}
