// Auto-generated by scripts/convert-services.mjs
export const SERVICE_PAGE_META = {
  "our_services": {
    "title": "Pest Control Services in Melbourne | 7 States Pest Control",
    "description": "Expert pest control services in Melbourne. Safe, eco-friendly solutions for homes & businesses. Ants, termites, rodents & more. Get a free quote!",
    "bodyClass": "wp-singular page-template page-template-elementor_header_footer page wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-7780"
  },
  "solar_panel_bird_proofing": {
    "title": "Solar Panel Bird Proofing Services in Melbourne",
    "description": "Protect your solar panels from birds with expert bird proofing services in Melbourne. Prevent damage and ensure efficiency. Get a free quote today!",
    "bodyClass": "wp-singular page-template page-template-elementor_header_footer page wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-1353"
  },
  "our_services_ant_pest_control": {
    "title": "Ant Pest Control Treatment in Melbourne - 7 States Pest Control",
    "description": "Searching for Ant Pest Control Treatment in Melbourne? At 7 States Pest Control, we can control ants and eliminate them from your property. With advanced pest control techniques, our services start at $170 Only.",
    "bodyClass": "wp-singular page-template page-template-elementor_header_footer page wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-766"
  },
  "our_services_bed_bug_treatment": {
    "title": "Bed Bug Exterminator in Melbourne | Bed Bugs Control & Extermination Services",
    "description": "We offers professional bed bug treatment in Melbourne starting at just $299. We treat bed frames, mattresses, couches, & carpets for complete eradication.",
    "bodyClass": "wp-singular page-template page-template-elementor_header_footer page wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-714"
  },
  "our_services_cockroach_control": {
    "title": "Pest Control for German Cockroaches in Melbourne - Starting Price $170.",
    "description": "Finding Pest control for German cockroaches in Melbourne? 7 States Pest Control offers you with effective cockroach control and elimination services.",
    "bodyClass": "wp-singular page-template page-template-elementor_header_footer page wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-716"
  },
  "our_services_mosquito_pest_control": {
    "title": "Mosquito pest control services in Melbourne - 7 States Pest Control",
    "description": "Eliminate mosquitoes from your office and home with pest control solutions. Consult 7 States Pest Control for mosquito pest control services. Starting price $170.",
    "bodyClass": "wp-singular page-template page-template-elementor_header_footer page wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-1463"
  },
  "our_services_fly_control": {
    "title": "Fly Control in Melbourne – Starting Price $170.",
    "description": "If you think it’s the right time to start doing something to eliminate moths from your house, hire 7 States Pest Control. At our company, our professionals assist you with effective Moth Control and elimination solutions.",
    "bodyClass": "wp-singular page-template page-template-elementor_header_footer page wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-1544"
  },
  "our_services_fox_pest_control_in_melbourne": {
    "title": "Fox Removal & Trapping Services in Melbourne | Starting $299",
    "description": "Need professional fox pest control in Melbourne? 7 States Pest Control offers licensed, humane fox removal and trapping services starting at $299. Get a free quote today.",
    "bodyClass": "wp-singular page-template page-template-elementor_header_footer page wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9877"
  },
  "our_services_mites_control": {
    "title": "Mites Control in Melbourne - 7 States Pest Control",
    "description": "Our astute pest controllers use state-of-the-art equipment for exterminating possums. Consult our knowledgeable professionals today for Possum Removal Control solutions. Starting price: $170.",
    "bodyClass": "wp-singular page-template page-template-elementor_header_footer page wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-1569"
  },
  "our_services_moth_control": {
    "title": "Carpet Moth Treatment in Melbourne | Starting Price $170",
    "description": "Finding Pest control professionals for Carpet moth treatment in Melbourne? At 7 States Pest Control, we offer you with top-quality Moth Control services.",
    "bodyClass": "wp-singular page-template page-template-elementor_header_footer page wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-1587"
  },
  "our_services_possum_pest_control": {
    "title": "Possum Pest Control Melbourne | Best Possum Removal",
    "description": "Expert possum removal in Melbourne. Safe possum control, dead possum removal, roof inspections & affordable possum removal services.",
    "bodyClass": "wp-singular page-template page-template-elementor_header_footer page wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10278"
  },
  "rodent_control_in_melbourne": {
    "title": "Rodent Control Melbourne | Affordable Mice & Rat Pest Control",
    "description": "Affordable & cheap rodent control in Melbourne. Mice pest control, rat pest control & rodent removal services in Melbourne by trusted experts. Book today!",
    "bodyClass": "wp-singular page-template page-template-elementor_header_footer page wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-1680"
  },
  "our_services_silverfish_treatment": {
    "title": "Silverfish Treatment in Melbourne | Starting Price $170 Only.",
    "description": "This small and silver-colored insect also poses significant health hazards that you cannot undermine. At 7 States Pest Control, we offer professional silverfish treatment to make your lives simpler.",
    "bodyClass": "wp-singular page-template page-template-elementor_header_footer page wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-1602"
  },
  "our_services_spider_control_treatment": {
    "title": "Spider Control Treatment in Melbourne - 7 States Pest Control",
    "description": "Searching Pest control professionals for Spider Control Treatment in Melbourne? At 7 States Pest Control, we offer spider control services starting at $170, with comprehensive experience in eliminating infestations from your property.",
    "bodyClass": "wp-singular page-template page-template-elementor_header_footer page wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-1626"
  },
  "our_services_termite_pest_control": {
    "title": "Termite Control Melbourne | Termite Treatment & Pest Control",
    "description": "Professional termite control Melbourne. Termite treatment, termite barrier & termite removal Melbourne by certified experts. Reliable termite pest control.",
    "bodyClass": "wp-singular page-template page-template-elementor_header_footer page wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10357"
  },
  "wasp_removal_melbourne": {
    "title": "Wasp Removal Melbourne | Wasp Nest Control & Exterminator",
    "description": "Affordable wasp removal Melbourne cost-friendly service. Expert wasp control, wasp nest removal & wasp exterminator in Melbourne. Get rid of wasps fast!",
    "bodyClass": "wp-singular page-template page-template-elementor_header_footer page wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-1638"
  },
  "our_services_end_of_lease_pest_control": {
    "title": "End of Lease Pest Control in Melbourne | 7 States",
    "description": "Affordable end of lease pest control in Melbourne. 100% bond-back service with same-day treatment. Trusted by tenants, agents & landlords. Book now!",
    "bodyClass": "wp-singular page-template page-template-elementor_header_footer page wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-1666"
  }
}
