/** Our Services page card order — matches https://7statespestcontrol.com.au/our-services/ */
export const ourServicesGridPages = [
  {
    slug: 'cockroach',
    title: 'Cockroach Control',
    path: '/our-services/cockroach-control',
    image: '/assets/images/Cockroaches.png-1_56844a04.webp',
    alt: 'cockroach pest control',
    widgetId: 'd018aa2',
    containerId: 'c402c97',
  },
  {
    slug: 'bed-bug',
    title: 'Bed Bug Treatment',
    path: '/our-services/bed-bug-treatment',
    image: '/assets/images/Bed-Bug.png_1da7e9d8.webp',
    alt: 'Bed Bug Pest Control',
    widgetId: '1c53f02',
    containerId: 'dda2999',
  },
  {
    slug: 'ant',
    title: 'Ant Pest Control',
    path: '/our-services/ant-pest-control',
    image: '/assets/images/ant-colony-insect-animals-pest-png_73d1a8ca.png',
    alt: 'Ant Pest Control',
    widgetId: '18f2f28',
    containerId: '4724110',
    imageWidth: 360,
    imageHeight: 360,
    imageClassName: 'Ant-new',
  },
  {
    slug: 'mites',
    title: 'Mites Control',
    path: '/our-services/mites-control',
    image: '/assets/images/Mite-Control.png_4c3b4b78.webp',
    alt: 'mites control',
    widgetId: 'f81459b',
    containerId: 'f78c4ce',
  },
  {
    slug: 'fly',
    title: 'Fly Control',
    path: '/our-services/fly-control',
    image: '/assets/images/Fly-Control.png_4cfa4c12.webp',
    alt: 'Fly-Control',
    widgetId: 'fe0b0cf',
    containerId: '787ee7e',
  },
  {
    slug: 'flea',
    title: 'Flea Treatment',
    path: '/flea-treatment',
    image: '/assets/images/Flea-Control.png_a5558f62.webp',
    alt: 'Flea Control',
    widgetId: 'd7a2d97',
    containerId: '94f2d22',
  },
  {
    slug: 'mosquito',
    title: 'Mosquito Pest Control',
    path: '/our-services/mosquito-pest-control',
    image: '/assets/images/Mosquito-Control.png_90777f1c.webp',
    alt: 'Mosquito pest Control',
    widgetId: '7543503',
    containerId: 'f2d7f17',
  },
  {
    slug: 'rodent',
    title: 'Rodent Control',
    path: '/rodent-control-in-melbourne',
    image: '/assets/images/Rodent-Control.png-1_0842a15c.webp',
    alt: 'Rodent Pest Control',
    widgetId: '112c6a0',
    containerId: '669a77c',
  },
  {
    slug: 'moth',
    title: 'Moth Control',
    path: '/our-services/moth-control',
    image: '/assets/images/Moth-Control.png-1_737c5080.webp',
    alt: 'Moth Control',
    widgetId: '6055ae2',
    containerId: '65c27c2',
  },
  {
    slug: 'wasp',
    title: 'Wasp Control Services',
    path: '/wasp-removal-melbourne',
    image: '/assets/images/Wasp-Removal.png-1_2802cb47.webp',
    alt: 'Wasp Removal melbourne',
    widgetId: 'd503178',
    containerId: '7f3940e',
  },
  {
    slug: 'spider',
    title: 'Spider Control Treatment',
    path: '/our-services/spider-control-treatment',
    image: '/assets/images/Spider-Control.png-2_18a07ad3.webp',
    alt: 'spider control',
    widgetId: '14d256c',
    containerId: 'a089861',
  },
  {
    slug: 'silverfish',
    title: 'Silverfish Treatment',
    path: '/our-services/silverfish-treatment',
    image: '/assets/images/Silver-Fish.png_cbd8da70.webp',
    alt: 'silver fish control',
    widgetId: 'd704cce',
    containerId: 'b6e2060',
  },
]

export const ourServicesGridRowIds = ['0395739', '9be12d8', '9d03c9b', '694d0ad']
