// Auto-generated by scripts/convert-blog-posts.mjs
export const BLOG_POST_PAGE_META = {
  "post_3_common_rodents_in_melbourne_homes_professional_rodent_control_insights_you_need": {
    "title": "Melbourne Rodent Control | 7 States Pest Control",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9639"
  },
  "post_5_myths_about_wasp_removal_melbourne_you_should_stop_believing": {
    "title": "Wasp Removal Melbourne: 5 Common Myths Debunked",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10626"
  },
  "post_5_surprising_facts_rodent_pest_control_experts_in_melbourne_want_you_to_know_in_2026": {
    "title": "Rodent Pest Control Melbourne: 5 Facts You Need to Know",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10270"
  },
  "post_6_types_of_wasps_you_should_know_and_how_pest_control_keeps_your_home_and_garden_safe": {
    "title": "6 Types of Wasps You Should Know | Wasp Nest Control Melbourne",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10317"
  },
  "post_7_states_pest_controls_smart_strategies_for_rodent_control_in_melbourne": {
    "title": "7 States Pest Control's Smart Rodent Control Strategies in Melbourne",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-7347"
  },
  "post_7_warning_signs_you_need_termite_control_in_your_melbourne_home": {
    "title": "Termite Control Melbourne: 7 Warning Signs",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10470"
  },
  "post_are_you_accidentally_feeding_rats_melbournes_top_at_home_mistakes": {
    "title": "Are You Feeding Rats? Rodent Removal in Melbourne",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9766"
  },
  "post_bed_bug_alert_in_september_tips_to_protect_your_melbourne_home": {
    "title": "Bed Bug Treatment Melbourne | September Pest Control Tips",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9540"
  },
  "post_bed_bug_removal_or_fly_control_in_melbourne_which_pest_is_a_bigger_threat": {
    "title": "Bed Bug & Fly Pest Control Services in Melbourne",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9582"
  },
  "post_bed_bug_treatment_melbourne_2026_must_read_guide_to_remove_bed_bugs_fast": {
    "title": "Bed Bug Treatment Melbourne 2026",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10402"
  },
  "post_buying_a_home_dont_skip_a_termite_inspection_in_melbourne": {
    "title": "Termite Inspection Melbourne | Home Buyers Guide",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10651"
  },
  "post_can_one_rat_inside_the_house_become_a_bigger_infestation_heres_the_truth": {
    "title": "Can One Rat Lead to an Infestation? | Affordable Rodent Control",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10595"
  },
  "post_crawling_spiders_in_your_kitchen_or_wardrobe_heres_how_melbourne_homes_can_stay_pest_free": {
    "title": "Spider Control and Removal Services in Melbourne – Keep Your Home Pest-Free",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-7434"
  },
  "post_do_i_need_rodent_control_after_renovation_the_truth_you_must_know": {
    "title": "Rodent Control After Renovation | Cheap Rodent Control Melbourne",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9195"
  },
  "post_do_you_know_the_signs_of_a_growing_wasp_infestation_in_melbourne_7_states_pest_control_explains": {
    "title": "Wasp Control in Melbourne: Signs of Infestation & Expert Help",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9785"
  },
  "post_every_pest_has_a_different_solution_inside_7_states_pest_controls_melbourne_treatment_methods": {
    "title": "Every Pest Has a Different Solution | Pest Control Melbourne",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10093"
  },
  "post_facing_a_pest_problem_in_your_melbourne_cafe_heres_what_you_need_to_know": {
    "title": "Pest Removal Melbourne for Cafés and Restaurants",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9565"
  },
  "post_found_a_wasp_nest_in_melbourne_heres_what_you_should_do": {
    "title": "Wasp Nest Melbourne: What To Do If You Find One",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10408"
  },
  "post_fox_control_services_melbourne_a_beginners_complete_guide_2026": {
    "title": "Fox Control Services Melbourne",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10415"
  },
  "post_fox_pest_control_melbourne_what_are_your_options_and_what_really_works": {
    "title": "Fox Pest Control Melbourne – Safe & Effective Solutions",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10384"
  },
  "post_fox_problems_in_melbourne_heres_how_experts_handle_it_safely": {
    "title": "Professional Fox Removal Services in Melbourne",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10099"
  },
  "post_how_do_i_choose_the_best_pest_control_service_in_melbourne": {
    "title": "Spider Control Services in Melbourne | Expert Pest Control for Your Home",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9531"
  },
  "post_how_melbournes_climate_affects_bed_bug_infestations": {
    "title": "Bed Bug Control Melbourne | How Climate Affects Infestations",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-7407"
  },
  "post_how_much_does_pest_control_in_melbourne_cost_in_2026": {
    "title": "Pest Control Melbourne Costs 2026 – Complete Guide",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9601"
  },
  "post_how_safe_is_your_workspace_if_you_skip_office_pest_control_7_states_pest_control_explain": {
    "title": "Office Pest Control Melbourne | Workplace Rodent Solutions",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9911"
  },
  "post_how_to_make_your_melbourne_home_wasp_free_7_proven_prevention_tips": {
    "title": "How to Make Your Melbourne Home Wasp-Free | 7 States Pest Control",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9516"
  },
  "post_how_to_safely_remove_a_wasp_nest_in_melbourne_expert_tips_for_2026": {
    "title": "2026 Safe Wasp Nest Removal Guide for Melbourne Homes",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9788"
  },
  "post_how_to_tell_if_bed_bugs_are_gone_post_treatment_tips_for_melbourne_homes": {
    "title": "Are Bed Bugs Really Gone? What to Expect After Treatment in Melbourne",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-7419"
  },
  "post_looking_for_spider_pest_control_services_in_melbourne": {
    "title": "Spider Pest Control In Melbourne | Safe & Affordable Solutions",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-7415"
  },
  "post_melbourne_wasp_removal_hacks_10_pro_secrets_you_dont_know": {
    "title": "Melbourne Wasp Removal Hacks: 10 Pro Secrets You Need",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10458"
  },
  "post_melbournes_hidden_infestations_how_bed_bugs_spread_how_professionals_stop_them": {
    "title": "Melbourne’s Hidden Infestations: Bed Bugs Control & Treatment",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9776"
  },
  "post_mice_control_in_melbourne_how_long_does_it_take_to_fully_get_rid_of_a_mice_problem": {
    "title": "Mice Control Melbourne: How Long Does It Take?",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10656"
  },
  "post_moving_into_a_new_home_heres_why_you_need_pre_treatment_pest_control": {
    "title": "Pre-Treatment Pest Control Melbourne | Secure Your New Home Before Moving In",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9465"
  },
  "post_office_pest_control_tips_every_melbourne_business_owner_should_follow": {
    "title": "Office Pest Control Melbourne: 10 Essential Tips for Businesses",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10594"
  },
  "post_one_bed_bug_can_turn_into_a_full_infestation_why_bed_bug_pest_control_melbourne_is_essential": {
    "title": "Bed Bug Pest Control Melbourne | Stop Infestations Fast",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10086"
  },
  "post_pest_control_melbourne_rats_why_restaurant_kitchens_are_the_1_target_for_rodents": {
    "title": "Pest Control Melbourne Rats: Why Restaurant Kitchens Are 1",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10612"
  },
  "post_roof_rat_control_removal_melbourne_7_states_pest_control": {
    "title": "Roof Rat Control Melbourne | 7 States Pest Control",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9608"
  },
  "post_spider_problems_in_melbourne_homes_signs_risks_and_effective_treatment": {
    "title": "Spider Pest Control Melbourne: Signs & Treatment",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10352"
  },
  "post_spider_removal_service_vs_termite_control_in_melbourne_which_one_does_your_home_actually_need": {
    "title": "Spider Removal vs Termite Control Melbourne",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10445"
  },
  "post_strange_noises_in_the_roof_you_may_need_possum_removal_in_melbourne": {
    "title": "Possum Removal Melbourne | Stop Roof Noises Fast",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10396"
  },
  "post_struggling_with_wasp_nests_at_your_warehouse_melbourne_wasp_removal_and_factory_pest_control_services_can_help": {
    "title": "Melbourne Wasp Removal & Factory Pest Control Services",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9596"
  },
  "post_the_bed_bug_battle_ends_here_expert_bed_bugs_treatment_in_melbourne_by_7_states_pest_control": {
    "title": "Bed Bugs Treatment Melbourne | 7 States Pest Control",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9619"
  },
  "post_the_dark_secret_above_your_ceiling_why_melbourne_homes_need_a_roof_cavity_check_every_year": {
    "title": "Roof Cavity Check | Pest Control Melbourne",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10614"
  },
  "post_the_lifecycle_of_a_spider_why_regular_treatments_matter": {
    "title": "Spider Pest Control Melbourne: Why Regular Treatments Are Key",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9470"
  },
  "post_the_smart_homeowners_guide_to_termite_barrier_protection_in_melbourne": {
    "title": "Termite Barrier & Termite Removal Melbourne Guide",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10621"
  },
  "post_the_truth_about_pest_control_melbourne_what_most_homeowners_dont_know": {
    "title": "The Truth About Pest Control Melbourne — What No One Tells You",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10471"
  },
  "post_think_its_just_one_wasp_heres_what_could_be_hiding_nearby": {
    "title": "Wasp Removal Melbourne: Hidden Nest Signs & Expert Control",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10582"
  },
  "post_think_spiders_are_harmless_5_health_problems_that_prove_you_need_pest_control_immediately": {
    "title": "Think Spiders Are Harmless? Get Expert Spider Removal Service in Melbourne",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9648"
  },
  "post_top_10_benefits_of_hiring_professionals_for_rodent_pest_control_in_melbourne": {
    "title": "Rodent Pest Control Melbourne | 10 Benefits of Experts",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9571"
  },
  "post_uncovering_the_secret_lives_of_ants_rodents_in_melbourne_homes_pest_exterminator_melbourne": {
    "title": "Ant & Rodent Control | Pest Exterminator Melbourne",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9624"
  },
  "post_unseen_unwanted_unstoppable_not_anymore_expert_spider_control_services_you_can_trust": {
    "title": "Spider Control Services Melbourne | 7 States Pest Control",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9613"
  },
  "post_wasp_nest_control_melbourne_7_proven_ways_to_keep_your_property_wasp_free": {
    "title": "Wasp Nest Control Melbourne | 7 Proven Methods",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10646"
  },
  "post_what_attracts_rats_to_melbourne_suburbs_and_how_7_states_pest_control_keeps_them_out": {
    "title": "What Attracts Rats to Melbourne? | 7 States Pest Control",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10459"
  },
  "post_what_colour_clothes_attract_wasps_outdoor_safety_tips_for_melbourne": {
    "title": "What Colour Clothes Attract Wasps? | Outdoor Wasp Safety Tips for Melbourne",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9197"
  },
  "post_what_makes_a_pest_problem_serious_in_melbourne_properties": {
    "title": "When Pest Problems Become Serious in Melbourne Homes",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10336"
  },
  "post_what_makes_spider_pest_control_in_melbourne_essential_for_schools_and_hotels": {
    "title": "Spider Pest Control Melbourne | Schools & Hotels",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9577"
  },
  "post_what_to_do_in_the_first_24_hours_of_a_rat_sighting_in_melbourne": {
    "title": "First 24 Hours of a Rat Sighting in Melbourne: What to Do",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9783"
  },
  "post_why_melbourne_homes_need_professional_termite_pest_control": {
    "title": "Professional Termite Pest Control in Melbourne",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10631"
  },
  "post_why_some_melbourne_homes_never_have_pest_problems": {
    "title": "Pest Control Melbourne | Why Some Homes Stay Pest-Free",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10638"
  },
  "post_why_your_cafe_restaurant_needs_pest_control_in_melbourne_here_are_5_key_reasons": {
    "title": "Spider Control Services for Cafés & Restaurants Melbourne",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10079"
  },
  "post_why_your_diy_traps_arent_working_the_reality_of_rodent_control_in_melbourne": {
    "title": "Expert Rodent Control Melbourne: Myths vs. Reality",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-10451"
  },
  "post_why_your_neighbours_rodent_problem_could_be_yours_too": {
    "title": "Rodent Pest Control Melbourne | Stop Neighbour Infestations",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9513"
  },
  "post_worried_about_wasp_nests_in_your_office_effective_wasp_control_melbourne_solutions": {
    "title": "Wasp Control Melbourne for Offices",
    "description": "",
    "bodyClass": "wp-singular single single-post wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-9559"
  }
}
