// Auto-generated by scripts/convert-blog.mjs
export const BLOG_PAGE_META = {
  blog: {
    title: "Expert Pest Control Tips & Advice | 7 States Pest Control Blog.",
    description: "Stay informed with expert pest control tips, advice, and insights from the 7 States Pest Control blog. Protect your home or business from pests today!",
    bodyClass: "wp-singular page-template page-template-elementor_header_footer page page-id-87 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-87",
  },
}
