// Auto-generated by scripts/extract-commercial-section-ids.mjs
export const COMMERCIAL_PAGE_CMS_SECTIONS = {
  "office-pest-control": {
    "about": {
      "counter": "cf735ac",
      "title": "bbd3149",
      "subtitle": "6b156f7",
      "intro": "6b156f7"
    },
    "whyChoose": {
      "eyebrow": "b4e0adb",
      "title": "625ccc2",
      "intro": "33beeec"
    },
    "contact": {
      "eyebrow": "e5f90ea",
      "title": "c28e1bf",
      "body": "07d0104",
      "button": "69faabb"
    },
    "services": {
      "eyebrow": "e794f2d",
      "title": "6c9b546",
      "intro": "525d2be"
    }
  },
  "restaurant-cafe-pest-control": {
    "about": {
      "counter": "10fbe05",
      "title": "a7ca4ac",
      "subtitle": null,
      "intro": null
    },
    "whyChoose": {
      "eyebrow": "ef37e23",
      "title": "9d951b9",
      "intro": "ac1bca2"
    },
    "contact": {
      "eyebrow": "493c991",
      "title": "0218e13",
      "body": "03f14e9",
      "button": null
    },
    "services": {
      "eyebrow": "5eee44d",
      "title": "5653b18",
      "intro": "f1792d0"
    }
  },
  "school-and-hospitality-facility-pest-control": {
    "about": {
      "counter": null,
      "title": null,
      "subtitle": "e1bdf2f",
      "intro": null
    },
    "whyChoose": {
      "eyebrow": "40e26c4",
      "title": "d2db9f5",
      "intro": "462599a"
    },
    "contact": {
      "eyebrow": "eed991b",
      "title": "06dbb5d",
      "body": "dee1e66",
      "button": null
    },
    "services": {
      "eyebrow": "e72ead3",
      "title": "b3f71fc",
      "intro": "9216c64"
    }
  },
  "warehouse-and-factory-pest-control-services-melbourne": {
    "about": {
      "counter": null,
      "title": null,
      "subtitle": null,
      "intro": null
    },
    "whyChoose": {
      "eyebrow": "cd86096",
      "title": "ab4bccf",
      "intro": "ba93f7b"
    },
    "contact": {
      "eyebrow": "0b49aea",
      "title": "a5f3bb3",
      "body": "7b9aa5a",
      "button": null
    },
    "services": {
      "eyebrow": "5751f84",
      "title": "0109a35",
      "intro": "2963f03"
    }
  },
  "commercial-pest-control": {
    "about": {},
    "whyChoose": {},
    "contact": {
      "eyebrow": "d694030",
      "title": "d694031",
      "body": "d694032",
      "button": "d694033"
    },
    "services": {
      "eyebrow": "d694020",
      "title": "d694021",
      "intro": "d694022"
    }
  }
}
