// Auto-generated by scripts/convert-contact.mjs
export const CONTACT_PAGE_META = {
  contact_us: {
    title: "Contact Us | 7 States Pest Control.",
    description: "Need pest control services in Melbourne? Contact 7 States Pest Control for expert solutions. Trusted professionals serving Melbourne and surrounding areas.",
    bodyClass: "wp-singular page-template page-template-elementor_header_footer page page-id-86 wp-custom-logo wp-embed-responsive wp-theme-hello-elementor elementor-default elementor-template-full-width elementor-kit-9 elementor-page elementor-page-86",
  },
}
