// Auto-generated by scripts/convert-blog-posts.mjs
import Post3CommonRodentsInMelbourneHomesProfessionalRodentControlInsightsYouNeedPostPage from './pages/blog/Post3CommonRodentsInMelbourneHomesProfessionalRodentControlInsightsYouNeedPostPage.jsx'
import Post5MythsAboutWaspRemovalMelbourneYouShouldStopBelievingPostPage from './pages/blog/Post5MythsAboutWaspRemovalMelbourneYouShouldStopBelievingPostPage.jsx'
import Post5SurprisingFactsRodentPestControlExpertsInMelbourneWantYouToKnowIn2026PostPage from './pages/blog/Post5SurprisingFactsRodentPestControlExpertsInMelbourneWantYouToKnowIn2026PostPage.jsx'
import Post6TypesOfWaspsYouShouldKnowAndHowPestControlKeepsYourHomeAndGardenSafePostPage from './pages/blog/Post6TypesOfWaspsYouShouldKnowAndHowPestControlKeepsYourHomeAndGardenSafePostPage.jsx'
import Post7StatesPestControlsSmartStrategiesForRodentControlInMelbournePostPage from './pages/blog/Post7StatesPestControlsSmartStrategiesForRodentControlInMelbournePostPage.jsx'
import Post7WarningSignsYouNeedTermiteControlInYourMelbourneHomePostPage from './pages/blog/Post7WarningSignsYouNeedTermiteControlInYourMelbourneHomePostPage.jsx'
import AreYouAccidentallyFeedingRatsMelbournesTopAtHomeMistakesPostPage from './pages/blog/AreYouAccidentallyFeedingRatsMelbournesTopAtHomeMistakesPostPage.jsx'
import BedBugAlertInSeptemberTipsToProtectYourMelbourneHomePostPage from './pages/blog/BedBugAlertInSeptemberTipsToProtectYourMelbourneHomePostPage.jsx'
import BedBugRemovalOrFlyControlInMelbourneWhichPestIsABiggerThreatPostPage from './pages/blog/BedBugRemovalOrFlyControlInMelbourneWhichPestIsABiggerThreatPostPage.jsx'
import BedBugTreatmentMelbourne2026MustReadGuideToRemoveBedBugsFastPostPage from './pages/blog/BedBugTreatmentMelbourne2026MustReadGuideToRemoveBedBugsFastPostPage.jsx'
import BuyingAHomeDontSkipATermiteInspectionInMelbournePostPage from './pages/blog/BuyingAHomeDontSkipATermiteInspectionInMelbournePostPage.jsx'
import CanOneRatInsideTheHouseBecomeABiggerInfestationHeresTheTruthPostPage from './pages/blog/CanOneRatInsideTheHouseBecomeABiggerInfestationHeresTheTruthPostPage.jsx'
import CrawlingSpidersInYourKitchenOrWardrobeHeresHowMelbourneHomesCanStayPestFreePostPage from './pages/blog/CrawlingSpidersInYourKitchenOrWardrobeHeresHowMelbourneHomesCanStayPestFreePostPage.jsx'
import DoINeedRodentControlAfterRenovationTheTruthYouMustKnowPostPage from './pages/blog/DoINeedRodentControlAfterRenovationTheTruthYouMustKnowPostPage.jsx'
import DoYouKnowTheSignsOfAGrowingWaspInfestationInMelbourne7StatesPestControlExplainsPostPage from './pages/blog/DoYouKnowTheSignsOfAGrowingWaspInfestationInMelbourne7StatesPestControlExplainsPostPage.jsx'
import EveryPestHasADifferentSolutionInside7StatesPestControlsMelbourneTreatmentMethodsPostPage from './pages/blog/EveryPestHasADifferentSolutionInside7StatesPestControlsMelbourneTreatmentMethodsPostPage.jsx'
import FacingAPestProblemInYourMelbourneCafeHeresWhatYouNeedToKnowPostPage from './pages/blog/FacingAPestProblemInYourMelbourneCafeHeresWhatYouNeedToKnowPostPage.jsx'
import FoundAWaspNestInMelbourneHeresWhatYouShouldDoPostPage from './pages/blog/FoundAWaspNestInMelbourneHeresWhatYouShouldDoPostPage.jsx'
import FoxControlServicesMelbourneABeginnersCompleteGuide2026PostPage from './pages/blog/FoxControlServicesMelbourneABeginnersCompleteGuide2026PostPage.jsx'
import FoxPestControlMelbourneWhatAreYourOptionsAndWhatReallyWorksPostPage from './pages/blog/FoxPestControlMelbourneWhatAreYourOptionsAndWhatReallyWorksPostPage.jsx'
import FoxProblemsInMelbourneHeresHowExpertsHandleItSafelyPostPage from './pages/blog/FoxProblemsInMelbourneHeresHowExpertsHandleItSafelyPostPage.jsx'
import HowDoIChooseTheBestPestControlServiceInMelbournePostPage from './pages/blog/HowDoIChooseTheBestPestControlServiceInMelbournePostPage.jsx'
import HowMelbournesClimateAffectsBedBugInfestationsPostPage from './pages/blog/HowMelbournesClimateAffectsBedBugInfestationsPostPage.jsx'
import HowMuchDoesPestControlInMelbourneCostIn2026PostPage from './pages/blog/HowMuchDoesPestControlInMelbourneCostIn2026PostPage.jsx'
import HowSafeIsYourWorkspaceIfYouSkipOfficePestControl7StatesPestControlExplainPostPage from './pages/blog/HowSafeIsYourWorkspaceIfYouSkipOfficePestControl7StatesPestControlExplainPostPage.jsx'
import HowToMakeYourMelbourneHomeWaspFree7ProvenPreventionTipsPostPage from './pages/blog/HowToMakeYourMelbourneHomeWaspFree7ProvenPreventionTipsPostPage.jsx'
import HowToSafelyRemoveAWaspNestInMelbourneExpertTipsFor2026PostPage from './pages/blog/HowToSafelyRemoveAWaspNestInMelbourneExpertTipsFor2026PostPage.jsx'
import HowToTellIfBedBugsAreGonePostTreatmentTipsForMelbourneHomesPostPage from './pages/blog/HowToTellIfBedBugsAreGonePostTreatmentTipsForMelbourneHomesPostPage.jsx'
import LookingForSpiderPestControlServicesInMelbournePostPage from './pages/blog/LookingForSpiderPestControlServicesInMelbournePostPage.jsx'
import MelbourneWaspRemovalHacks10ProSecretsYouDontKnowPostPage from './pages/blog/MelbourneWaspRemovalHacks10ProSecretsYouDontKnowPostPage.jsx'
import MelbournesHiddenInfestationsHowBedBugsSpreadHowProfessionalsStopThemPostPage from './pages/blog/MelbournesHiddenInfestationsHowBedBugsSpreadHowProfessionalsStopThemPostPage.jsx'
import MiceControlInMelbourneHowLongDoesItTakeToFullyGetRidOfAMiceProblemPostPage from './pages/blog/MiceControlInMelbourneHowLongDoesItTakeToFullyGetRidOfAMiceProblemPostPage.jsx'
import MovingIntoANewHomeHeresWhyYouNeedPreTreatmentPestControlPostPage from './pages/blog/MovingIntoANewHomeHeresWhyYouNeedPreTreatmentPestControlPostPage.jsx'
import OfficePestControlTipsEveryMelbourneBusinessOwnerShouldFollowPostPage from './pages/blog/OfficePestControlTipsEveryMelbourneBusinessOwnerShouldFollowPostPage.jsx'
import OneBedBugCanTurnIntoAFullInfestationWhyBedBugPestControlMelbourneIsEssentialPostPage from './pages/blog/OneBedBugCanTurnIntoAFullInfestationWhyBedBugPestControlMelbourneIsEssentialPostPage.jsx'
import PestControlMelbourneRatsWhyRestaurantKitchensAreThe1TargetForRodentsPostPage from './pages/blog/PestControlMelbourneRatsWhyRestaurantKitchensAreThe1TargetForRodentsPostPage.jsx'
import RoofRatControlRemovalMelbourne7StatesPestControlPostPage from './pages/blog/RoofRatControlRemovalMelbourne7StatesPestControlPostPage.jsx'
import SpiderProblemsInMelbourneHomesSignsRisksAndEffectiveTreatmentPostPage from './pages/blog/SpiderProblemsInMelbourneHomesSignsRisksAndEffectiveTreatmentPostPage.jsx'
import SpiderRemovalServiceVsTermiteControlInMelbourneWhichOneDoesYourHomeActuallyNeedPostPage from './pages/blog/SpiderRemovalServiceVsTermiteControlInMelbourneWhichOneDoesYourHomeActuallyNeedPostPage.jsx'
import StrangeNoisesInTheRoofYouMayNeedPossumRemovalInMelbournePostPage from './pages/blog/StrangeNoisesInTheRoofYouMayNeedPossumRemovalInMelbournePostPage.jsx'
import StrugglingWithWaspNestsAtYourWarehouseMelbourneWaspRemovalAndFactoryPestControlServicesCanHelpPostPage from './pages/blog/StrugglingWithWaspNestsAtYourWarehouseMelbourneWaspRemovalAndFactoryPestControlServicesCanHelpPostPage.jsx'
import TheBedBugBattleEndsHereExpertBedBugsTreatmentInMelbourneBy7StatesPestControlPostPage from './pages/blog/TheBedBugBattleEndsHereExpertBedBugsTreatmentInMelbourneBy7StatesPestControlPostPage.jsx'
import TheDarkSecretAboveYourCeilingWhyMelbourneHomesNeedARoofCavityCheckEveryYearPostPage from './pages/blog/TheDarkSecretAboveYourCeilingWhyMelbourneHomesNeedARoofCavityCheckEveryYearPostPage.jsx'
import TheLifecycleOfASpiderWhyRegularTreatmentsMatterPostPage from './pages/blog/TheLifecycleOfASpiderWhyRegularTreatmentsMatterPostPage.jsx'
import TheSmartHomeownersGuideToTermiteBarrierProtectionInMelbournePostPage from './pages/blog/TheSmartHomeownersGuideToTermiteBarrierProtectionInMelbournePostPage.jsx'
import TheTruthAboutPestControlMelbourneWhatMostHomeownersDontKnowPostPage from './pages/blog/TheTruthAboutPestControlMelbourneWhatMostHomeownersDontKnowPostPage.jsx'
import ThinkItsJustOneWaspHeresWhatCouldBeHidingNearbyPostPage from './pages/blog/ThinkItsJustOneWaspHeresWhatCouldBeHidingNearbyPostPage.jsx'
import ThinkSpidersAreHarmless5HealthProblemsThatProveYouNeedPestControlImmediatelyPostPage from './pages/blog/ThinkSpidersAreHarmless5HealthProblemsThatProveYouNeedPestControlImmediatelyPostPage.jsx'
import Top10BenefitsOfHiringProfessionalsForRodentPestControlInMelbournePostPage from './pages/blog/Top10BenefitsOfHiringProfessionalsForRodentPestControlInMelbournePostPage.jsx'
import UncoveringTheSecretLivesOfAntsRodentsInMelbourneHomesPestExterminatorMelbournePostPage from './pages/blog/UncoveringTheSecretLivesOfAntsRodentsInMelbourneHomesPestExterminatorMelbournePostPage.jsx'
import UnseenUnwantedUnstoppableNotAnymoreExpertSpiderControlServicesYouCanTrustPostPage from './pages/blog/UnseenUnwantedUnstoppableNotAnymoreExpertSpiderControlServicesYouCanTrustPostPage.jsx'
import WaspNestControlMelbourne7ProvenWaysToKeepYourPropertyWaspFreePostPage from './pages/blog/WaspNestControlMelbourne7ProvenWaysToKeepYourPropertyWaspFreePostPage.jsx'
import WhatAttractsRatsToMelbourneSuburbsAndHow7StatesPestControlKeepsThemOutPostPage from './pages/blog/WhatAttractsRatsToMelbourneSuburbsAndHow7StatesPestControlKeepsThemOutPostPage.jsx'
import WhatColourClothesAttractWaspsOutdoorSafetyTipsForMelbournePostPage from './pages/blog/WhatColourClothesAttractWaspsOutdoorSafetyTipsForMelbournePostPage.jsx'
import WhatMakesAPestProblemSeriousInMelbournePropertiesPostPage from './pages/blog/WhatMakesAPestProblemSeriousInMelbournePropertiesPostPage.jsx'
import WhatMakesSpiderPestControlInMelbourneEssentialForSchoolsAndHotelsPostPage from './pages/blog/WhatMakesSpiderPestControlInMelbourneEssentialForSchoolsAndHotelsPostPage.jsx'
import WhatToDoInTheFirst24HoursOfARatSightingInMelbournePostPage from './pages/blog/WhatToDoInTheFirst24HoursOfARatSightingInMelbournePostPage.jsx'
import WhyMelbourneHomesNeedProfessionalTermitePestControlPostPage from './pages/blog/WhyMelbourneHomesNeedProfessionalTermitePestControlPostPage.jsx'
import WhySomeMelbourneHomesNeverHavePestProblemsPostPage from './pages/blog/WhySomeMelbourneHomesNeverHavePestProblemsPostPage.jsx'
import WhyYourCafeRestaurantNeedsPestControlInMelbourneHereAre5KeyReasonsPostPage from './pages/blog/WhyYourCafeRestaurantNeedsPestControlInMelbourneHereAre5KeyReasonsPostPage.jsx'
import WhyYourDiyTrapsArentWorkingTheRealityOfRodentControlInMelbournePostPage from './pages/blog/WhyYourDiyTrapsArentWorkingTheRealityOfRodentControlInMelbournePostPage.jsx'
import WhyYourNeighboursRodentProblemCouldBeYoursTooPostPage from './pages/blog/WhyYourNeighboursRodentProblemCouldBeYoursTooPostPage.jsx'
import WorriedAboutWaspNestsInYourOfficeEffectiveWaspControlMelbourneSolutionsPostPage from './pages/blog/WorriedAboutWaspNestsInYourOfficeEffectiveWaspControlMelbourneSolutionsPostPage.jsx'

export const blogPostRoutes = [
  { path: '3-common-rodents-in-melbourne-homes-professional-rodent-control-insights-you-need', element: <Post3CommonRodentsInMelbourneHomesProfessionalRodentControlInsightsYouNeedPostPage /> },
  { path: '3-common-rodents-in-melbourne-homes-professional-rodent-control-insights-you-need/', element: <Post3CommonRodentsInMelbourneHomesProfessionalRodentControlInsightsYouNeedPostPage /> },
  { path: '5-myths-about-wasp-removal-melbourne-you-should-stop-believing', element: <Post5MythsAboutWaspRemovalMelbourneYouShouldStopBelievingPostPage /> },
  { path: '5-myths-about-wasp-removal-melbourne-you-should-stop-believing/', element: <Post5MythsAboutWaspRemovalMelbourneYouShouldStopBelievingPostPage /> },
  { path: '5-surprising-facts-rodent-pest-control-experts-in-melbourne-want-you-to-know-in-2026', element: <Post5SurprisingFactsRodentPestControlExpertsInMelbourneWantYouToKnowIn2026PostPage /> },
  { path: '5-surprising-facts-rodent-pest-control-experts-in-melbourne-want-you-to-know-in-2026/', element: <Post5SurprisingFactsRodentPestControlExpertsInMelbourneWantYouToKnowIn2026PostPage /> },
  { path: '6-types-of-wasps-you-should-know-and-how-pest-control-keeps-your-home-and-garden-safe', element: <Post6TypesOfWaspsYouShouldKnowAndHowPestControlKeepsYourHomeAndGardenSafePostPage /> },
  { path: '6-types-of-wasps-you-should-know-and-how-pest-control-keeps-your-home-and-garden-safe/', element: <Post6TypesOfWaspsYouShouldKnowAndHowPestControlKeepsYourHomeAndGardenSafePostPage /> },
  { path: '7-states-pest-controls-smart-strategies-for-rodent-control-in-melbourne', element: <Post7StatesPestControlsSmartStrategiesForRodentControlInMelbournePostPage /> },
  { path: '7-states-pest-controls-smart-strategies-for-rodent-control-in-melbourne/', element: <Post7StatesPestControlsSmartStrategiesForRodentControlInMelbournePostPage /> },
  { path: '7-warning-signs-you-need-termite-control-in-your-melbourne-home', element: <Post7WarningSignsYouNeedTermiteControlInYourMelbourneHomePostPage /> },
  { path: '7-warning-signs-you-need-termite-control-in-your-melbourne-home/', element: <Post7WarningSignsYouNeedTermiteControlInYourMelbourneHomePostPage /> },
  { path: 'are-you-accidentally-feeding-rats-melbournes-top-at-home-mistakes', element: <AreYouAccidentallyFeedingRatsMelbournesTopAtHomeMistakesPostPage /> },
  { path: 'are-you-accidentally-feeding-rats-melbournes-top-at-home-mistakes/', element: <AreYouAccidentallyFeedingRatsMelbournesTopAtHomeMistakesPostPage /> },
  { path: 'bed-bug-alert-in-september-tips-to-protect-your-melbourne-home', element: <BedBugAlertInSeptemberTipsToProtectYourMelbourneHomePostPage /> },
  { path: 'bed-bug-alert-in-september-tips-to-protect-your-melbourne-home/', element: <BedBugAlertInSeptemberTipsToProtectYourMelbourneHomePostPage /> },
  { path: 'bed-bug-removal-or-fly-control-in-melbourne-which-pest-is-a-bigger-threat', element: <BedBugRemovalOrFlyControlInMelbourneWhichPestIsABiggerThreatPostPage /> },
  { path: 'bed-bug-removal-or-fly-control-in-melbourne-which-pest-is-a-bigger-threat/', element: <BedBugRemovalOrFlyControlInMelbourneWhichPestIsABiggerThreatPostPage /> },
  { path: 'bed-bug-treatment-melbourne-2026-must-read-guide-to-remove-bed-bugs-fast', element: <BedBugTreatmentMelbourne2026MustReadGuideToRemoveBedBugsFastPostPage /> },
  { path: 'bed-bug-treatment-melbourne-2026-must-read-guide-to-remove-bed-bugs-fast/', element: <BedBugTreatmentMelbourne2026MustReadGuideToRemoveBedBugsFastPostPage /> },
  { path: 'buying-a-home-dont-skip-a-termite-inspection-in-melbourne', element: <BuyingAHomeDontSkipATermiteInspectionInMelbournePostPage /> },
  { path: 'buying-a-home-dont-skip-a-termite-inspection-in-melbourne/', element: <BuyingAHomeDontSkipATermiteInspectionInMelbournePostPage /> },
  { path: 'can-one-rat-inside-the-house-become-a-bigger-infestation-heres-the-truth', element: <CanOneRatInsideTheHouseBecomeABiggerInfestationHeresTheTruthPostPage /> },
  { path: 'can-one-rat-inside-the-house-become-a-bigger-infestation-heres-the-truth/', element: <CanOneRatInsideTheHouseBecomeABiggerInfestationHeresTheTruthPostPage /> },
  { path: 'crawling-spiders-in-your-kitchen-or-wardrobe-heres-how-melbourne-homes-can-stay-pest-free', element: <CrawlingSpidersInYourKitchenOrWardrobeHeresHowMelbourneHomesCanStayPestFreePostPage /> },
  { path: 'crawling-spiders-in-your-kitchen-or-wardrobe-heres-how-melbourne-homes-can-stay-pest-free/', element: <CrawlingSpidersInYourKitchenOrWardrobeHeresHowMelbourneHomesCanStayPestFreePostPage /> },
  { path: 'do-i-need-rodent-control-after-renovation-the-truth-you-must-know', element: <DoINeedRodentControlAfterRenovationTheTruthYouMustKnowPostPage /> },
  { path: 'do-i-need-rodent-control-after-renovation-the-truth-you-must-know/', element: <DoINeedRodentControlAfterRenovationTheTruthYouMustKnowPostPage /> },
  { path: 'do-you-know-the-signs-of-a-growing-wasp-infestation-in-melbourne-7-states-pest-control-explains', element: <DoYouKnowTheSignsOfAGrowingWaspInfestationInMelbourne7StatesPestControlExplainsPostPage /> },
  { path: 'do-you-know-the-signs-of-a-growing-wasp-infestation-in-melbourne-7-states-pest-control-explains/', element: <DoYouKnowTheSignsOfAGrowingWaspInfestationInMelbourne7StatesPestControlExplainsPostPage /> },
  { path: 'every-pest-has-a-different-solution-inside-7-states-pest-controls-melbourne-treatment-methods', element: <EveryPestHasADifferentSolutionInside7StatesPestControlsMelbourneTreatmentMethodsPostPage /> },
  { path: 'every-pest-has-a-different-solution-inside-7-states-pest-controls-melbourne-treatment-methods/', element: <EveryPestHasADifferentSolutionInside7StatesPestControlsMelbourneTreatmentMethodsPostPage /> },
  { path: 'facing-a-pest-problem-in-your-melbourne-cafe-heres-what-you-need-to-know', element: <FacingAPestProblemInYourMelbourneCafeHeresWhatYouNeedToKnowPostPage /> },
  { path: 'facing-a-pest-problem-in-your-melbourne-cafe-heres-what-you-need-to-know/', element: <FacingAPestProblemInYourMelbourneCafeHeresWhatYouNeedToKnowPostPage /> },
  { path: 'found-a-wasp-nest-in-melbourne-heres-what-you-should-do', element: <FoundAWaspNestInMelbourneHeresWhatYouShouldDoPostPage /> },
  { path: 'found-a-wasp-nest-in-melbourne-heres-what-you-should-do/', element: <FoundAWaspNestInMelbourneHeresWhatYouShouldDoPostPage /> },
  { path: 'fox-control-services-melbourne-a-beginners-complete-guide-2026', element: <FoxControlServicesMelbourneABeginnersCompleteGuide2026PostPage /> },
  { path: 'fox-control-services-melbourne-a-beginners-complete-guide-2026/', element: <FoxControlServicesMelbourneABeginnersCompleteGuide2026PostPage /> },
  { path: 'fox-pest-control-melbourne-what-are-your-options-and-what-really-works', element: <FoxPestControlMelbourneWhatAreYourOptionsAndWhatReallyWorksPostPage /> },
  { path: 'fox-pest-control-melbourne-what-are-your-options-and-what-really-works/', element: <FoxPestControlMelbourneWhatAreYourOptionsAndWhatReallyWorksPostPage /> },
  { path: 'fox-problems-in-melbourne-heres-how-experts-handle-it-safely', element: <FoxProblemsInMelbourneHeresHowExpertsHandleItSafelyPostPage /> },
  { path: 'fox-problems-in-melbourne-heres-how-experts-handle-it-safely/', element: <FoxProblemsInMelbourneHeresHowExpertsHandleItSafelyPostPage /> },
  { path: 'how-do-i-choose-the-best-pest-control-service-in-melbourne', element: <HowDoIChooseTheBestPestControlServiceInMelbournePostPage /> },
  { path: 'how-do-i-choose-the-best-pest-control-service-in-melbourne/', element: <HowDoIChooseTheBestPestControlServiceInMelbournePostPage /> },
  { path: 'how-melbournes-climate-affects-bed-bug-infestations', element: <HowMelbournesClimateAffectsBedBugInfestationsPostPage /> },
  { path: 'how-melbournes-climate-affects-bed-bug-infestations/', element: <HowMelbournesClimateAffectsBedBugInfestationsPostPage /> },
  { path: 'how-much-does-pest-control-in-melbourne-cost-in-2026', element: <HowMuchDoesPestControlInMelbourneCostIn2026PostPage /> },
  { path: 'how-much-does-pest-control-in-melbourne-cost-in-2026/', element: <HowMuchDoesPestControlInMelbourneCostIn2026PostPage /> },
  { path: 'how-safe-is-your-workspace-if-you-skip-office-pest-control-7-states-pest-control-explain', element: <HowSafeIsYourWorkspaceIfYouSkipOfficePestControl7StatesPestControlExplainPostPage /> },
  { path: 'how-safe-is-your-workspace-if-you-skip-office-pest-control-7-states-pest-control-explain/', element: <HowSafeIsYourWorkspaceIfYouSkipOfficePestControl7StatesPestControlExplainPostPage /> },
  { path: 'how-to-make-your-melbourne-home-wasp-free-7-proven-prevention-tips', element: <HowToMakeYourMelbourneHomeWaspFree7ProvenPreventionTipsPostPage /> },
  { path: 'how-to-make-your-melbourne-home-wasp-free-7-proven-prevention-tips/', element: <HowToMakeYourMelbourneHomeWaspFree7ProvenPreventionTipsPostPage /> },
  { path: 'how-to-safely-remove-a-wasp-nest-in-melbourne-expert-tips-for-2026', element: <HowToSafelyRemoveAWaspNestInMelbourneExpertTipsFor2026PostPage /> },
  { path: 'how-to-safely-remove-a-wasp-nest-in-melbourne-expert-tips-for-2026/', element: <HowToSafelyRemoveAWaspNestInMelbourneExpertTipsFor2026PostPage /> },
  { path: 'how-to-tell-if-bed-bugs-are-gone-post-treatment-tips-for-melbourne-homes', element: <HowToTellIfBedBugsAreGonePostTreatmentTipsForMelbourneHomesPostPage /> },
  { path: 'how-to-tell-if-bed-bugs-are-gone-post-treatment-tips-for-melbourne-homes/', element: <HowToTellIfBedBugsAreGonePostTreatmentTipsForMelbourneHomesPostPage /> },
  { path: 'looking-for-spider-pest-control-services-in-melbourne', element: <LookingForSpiderPestControlServicesInMelbournePostPage /> },
  { path: 'looking-for-spider-pest-control-services-in-melbourne/', element: <LookingForSpiderPestControlServicesInMelbournePostPage /> },
  { path: 'melbourne-wasp-removal-hacks-10-pro-secrets-you-dont-know', element: <MelbourneWaspRemovalHacks10ProSecretsYouDontKnowPostPage /> },
  { path: 'melbourne-wasp-removal-hacks-10-pro-secrets-you-dont-know/', element: <MelbourneWaspRemovalHacks10ProSecretsYouDontKnowPostPage /> },
  { path: 'melbournes-hidden-infestations-how-bed-bugs-spread-how-professionals-stop-them', element: <MelbournesHiddenInfestationsHowBedBugsSpreadHowProfessionalsStopThemPostPage /> },
  { path: 'melbournes-hidden-infestations-how-bed-bugs-spread-how-professionals-stop-them/', element: <MelbournesHiddenInfestationsHowBedBugsSpreadHowProfessionalsStopThemPostPage /> },
  { path: 'mice-control-in-melbourne-how-long-does-it-take-to-fully-get-rid-of-a-mice-problem', element: <MiceControlInMelbourneHowLongDoesItTakeToFullyGetRidOfAMiceProblemPostPage /> },
  { path: 'mice-control-in-melbourne-how-long-does-it-take-to-fully-get-rid-of-a-mice-problem/', element: <MiceControlInMelbourneHowLongDoesItTakeToFullyGetRidOfAMiceProblemPostPage /> },
  { path: 'moving-into-a-new-home-heres-why-you-need-pre-treatment-pest-control', element: <MovingIntoANewHomeHeresWhyYouNeedPreTreatmentPestControlPostPage /> },
  { path: 'moving-into-a-new-home-heres-why-you-need-pre-treatment-pest-control/', element: <MovingIntoANewHomeHeresWhyYouNeedPreTreatmentPestControlPostPage /> },
  { path: 'office-pest-control-tips-every-melbourne-business-owner-should-follow', element: <OfficePestControlTipsEveryMelbourneBusinessOwnerShouldFollowPostPage /> },
  { path: 'office-pest-control-tips-every-melbourne-business-owner-should-follow/', element: <OfficePestControlTipsEveryMelbourneBusinessOwnerShouldFollowPostPage /> },
  { path: 'one-bed-bug-can-turn-into-a-full-infestation-why-bed-bug-pest-control-melbourne-is-essential', element: <OneBedBugCanTurnIntoAFullInfestationWhyBedBugPestControlMelbourneIsEssentialPostPage /> },
  { path: 'one-bed-bug-can-turn-into-a-full-infestation-why-bed-bug-pest-control-melbourne-is-essential/', element: <OneBedBugCanTurnIntoAFullInfestationWhyBedBugPestControlMelbourneIsEssentialPostPage /> },
  { path: 'pest-control-melbourne-rats-why-restaurant-kitchens-are-the-1-target-for-rodents', element: <PestControlMelbourneRatsWhyRestaurantKitchensAreThe1TargetForRodentsPostPage /> },
  { path: 'pest-control-melbourne-rats-why-restaurant-kitchens-are-the-1-target-for-rodents/', element: <PestControlMelbourneRatsWhyRestaurantKitchensAreThe1TargetForRodentsPostPage /> },
  { path: 'roof-rat-control-removal-melbourne-7-states-pest-control', element: <RoofRatControlRemovalMelbourne7StatesPestControlPostPage /> },
  { path: 'roof-rat-control-removal-melbourne-7-states-pest-control/', element: <RoofRatControlRemovalMelbourne7StatesPestControlPostPage /> },
  { path: 'spider-problems-in-melbourne-homes-signs-risks-and-effective-treatment', element: <SpiderProblemsInMelbourneHomesSignsRisksAndEffectiveTreatmentPostPage /> },
  { path: 'spider-problems-in-melbourne-homes-signs-risks-and-effective-treatment/', element: <SpiderProblemsInMelbourneHomesSignsRisksAndEffectiveTreatmentPostPage /> },
  { path: 'spider-removal-service-vs-termite-control-in-melbourne-which-one-does-your-home-actually-need', element: <SpiderRemovalServiceVsTermiteControlInMelbourneWhichOneDoesYourHomeActuallyNeedPostPage /> },
  { path: 'spider-removal-service-vs-termite-control-in-melbourne-which-one-does-your-home-actually-need/', element: <SpiderRemovalServiceVsTermiteControlInMelbourneWhichOneDoesYourHomeActuallyNeedPostPage /> },
  { path: 'strange-noises-in-the-roof-you-may-need-possum-removal-in-melbourne', element: <StrangeNoisesInTheRoofYouMayNeedPossumRemovalInMelbournePostPage /> },
  { path: 'strange-noises-in-the-roof-you-may-need-possum-removal-in-melbourne/', element: <StrangeNoisesInTheRoofYouMayNeedPossumRemovalInMelbournePostPage /> },
  { path: 'struggling-with-wasp-nests-at-your-warehouse-melbourne-wasp-removal-and-factory-pest-control-services-can-help', element: <StrugglingWithWaspNestsAtYourWarehouseMelbourneWaspRemovalAndFactoryPestControlServicesCanHelpPostPage /> },
  { path: 'struggling-with-wasp-nests-at-your-warehouse-melbourne-wasp-removal-and-factory-pest-control-services-can-help/', element: <StrugglingWithWaspNestsAtYourWarehouseMelbourneWaspRemovalAndFactoryPestControlServicesCanHelpPostPage /> },
  { path: 'the-bed-bug-battle-ends-here-expert-bed-bugs-treatment-in-melbourne-by-7-states-pest-control', element: <TheBedBugBattleEndsHereExpertBedBugsTreatmentInMelbourneBy7StatesPestControlPostPage /> },
  { path: 'the-bed-bug-battle-ends-here-expert-bed-bugs-treatment-in-melbourne-by-7-states-pest-control/', element: <TheBedBugBattleEndsHereExpertBedBugsTreatmentInMelbourneBy7StatesPestControlPostPage /> },
  { path: 'the-dark-secret-above-your-ceiling-why-melbourne-homes-need-a-roof-cavity-check-every-year', element: <TheDarkSecretAboveYourCeilingWhyMelbourneHomesNeedARoofCavityCheckEveryYearPostPage /> },
  { path: 'the-dark-secret-above-your-ceiling-why-melbourne-homes-need-a-roof-cavity-check-every-year/', element: <TheDarkSecretAboveYourCeilingWhyMelbourneHomesNeedARoofCavityCheckEveryYearPostPage /> },
  { path: 'the-lifecycle-of-a-spider-why-regular-treatments-matter', element: <TheLifecycleOfASpiderWhyRegularTreatmentsMatterPostPage /> },
  { path: 'the-lifecycle-of-a-spider-why-regular-treatments-matter/', element: <TheLifecycleOfASpiderWhyRegularTreatmentsMatterPostPage /> },
  { path: 'the-smart-homeowners-guide-to-termite-barrier-protection-in-melbourne', element: <TheSmartHomeownersGuideToTermiteBarrierProtectionInMelbournePostPage /> },
  { path: 'the-smart-homeowners-guide-to-termite-barrier-protection-in-melbourne/', element: <TheSmartHomeownersGuideToTermiteBarrierProtectionInMelbournePostPage /> },
  { path: 'the-truth-about-pest-control-melbourne-what-most-homeowners-dont-know', element: <TheTruthAboutPestControlMelbourneWhatMostHomeownersDontKnowPostPage /> },
  { path: 'the-truth-about-pest-control-melbourne-what-most-homeowners-dont-know/', element: <TheTruthAboutPestControlMelbourneWhatMostHomeownersDontKnowPostPage /> },
  { path: 'think-its-just-one-wasp-heres-what-could-be-hiding-nearby', element: <ThinkItsJustOneWaspHeresWhatCouldBeHidingNearbyPostPage /> },
  { path: 'think-its-just-one-wasp-heres-what-could-be-hiding-nearby/', element: <ThinkItsJustOneWaspHeresWhatCouldBeHidingNearbyPostPage /> },
  { path: 'think-spiders-are-harmless-5-health-problems-that-prove-you-need-pest-control-immediately', element: <ThinkSpidersAreHarmless5HealthProblemsThatProveYouNeedPestControlImmediatelyPostPage /> },
  { path: 'think-spiders-are-harmless-5-health-problems-that-prove-you-need-pest-control-immediately/', element: <ThinkSpidersAreHarmless5HealthProblemsThatProveYouNeedPestControlImmediatelyPostPage /> },
  { path: 'top-10-benefits-of-hiring-professionals-for-rodent-pest-control-in-melbourne', element: <Top10BenefitsOfHiringProfessionalsForRodentPestControlInMelbournePostPage /> },
  { path: 'top-10-benefits-of-hiring-professionals-for-rodent-pest-control-in-melbourne/', element: <Top10BenefitsOfHiringProfessionalsForRodentPestControlInMelbournePostPage /> },
  { path: 'uncovering-the-secret-lives-of-ants-rodents-in-melbourne-homes-pest-exterminator-melbourne', element: <UncoveringTheSecretLivesOfAntsRodentsInMelbourneHomesPestExterminatorMelbournePostPage /> },
  { path: 'uncovering-the-secret-lives-of-ants-rodents-in-melbourne-homes-pest-exterminator-melbourne/', element: <UncoveringTheSecretLivesOfAntsRodentsInMelbourneHomesPestExterminatorMelbournePostPage /> },
  { path: 'unseen-unwanted-unstoppable-not-anymore-expert-spider-control-services-you-can-trust', element: <UnseenUnwantedUnstoppableNotAnymoreExpertSpiderControlServicesYouCanTrustPostPage /> },
  { path: 'unseen-unwanted-unstoppable-not-anymore-expert-spider-control-services-you-can-trust/', element: <UnseenUnwantedUnstoppableNotAnymoreExpertSpiderControlServicesYouCanTrustPostPage /> },
  { path: 'wasp-nest-control-melbourne-7-proven-ways-to-keep-your-property-wasp-free', element: <WaspNestControlMelbourne7ProvenWaysToKeepYourPropertyWaspFreePostPage /> },
  { path: 'wasp-nest-control-melbourne-7-proven-ways-to-keep-your-property-wasp-free/', element: <WaspNestControlMelbourne7ProvenWaysToKeepYourPropertyWaspFreePostPage /> },
  { path: 'what-attracts-rats-to-melbourne-suburbs-and-how-7-states-pest-control-keeps-them-out', element: <WhatAttractsRatsToMelbourneSuburbsAndHow7StatesPestControlKeepsThemOutPostPage /> },
  { path: 'what-attracts-rats-to-melbourne-suburbs-and-how-7-states-pest-control-keeps-them-out/', element: <WhatAttractsRatsToMelbourneSuburbsAndHow7StatesPestControlKeepsThemOutPostPage /> },
  { path: 'what-colour-clothes-attract-wasps-outdoor-safety-tips-for-melbourne', element: <WhatColourClothesAttractWaspsOutdoorSafetyTipsForMelbournePostPage /> },
  { path: 'what-colour-clothes-attract-wasps-outdoor-safety-tips-for-melbourne/', element: <WhatColourClothesAttractWaspsOutdoorSafetyTipsForMelbournePostPage /> },
  { path: 'what-makes-a-pest-problem-serious-in-melbourne-properties', element: <WhatMakesAPestProblemSeriousInMelbournePropertiesPostPage /> },
  { path: 'what-makes-a-pest-problem-serious-in-melbourne-properties/', element: <WhatMakesAPestProblemSeriousInMelbournePropertiesPostPage /> },
  { path: 'what-makes-spider-pest-control-in-melbourne-essential-for-schools-and-hotels', element: <WhatMakesSpiderPestControlInMelbourneEssentialForSchoolsAndHotelsPostPage /> },
  { path: 'what-makes-spider-pest-control-in-melbourne-essential-for-schools-and-hotels/', element: <WhatMakesSpiderPestControlInMelbourneEssentialForSchoolsAndHotelsPostPage /> },
  { path: 'what-to-do-in-the-first-24-hours-of-a-rat-sighting-in-melbourne', element: <WhatToDoInTheFirst24HoursOfARatSightingInMelbournePostPage /> },
  { path: 'what-to-do-in-the-first-24-hours-of-a-rat-sighting-in-melbourne/', element: <WhatToDoInTheFirst24HoursOfARatSightingInMelbournePostPage /> },
  { path: 'why-melbourne-homes-need-professional-termite-pest-control', element: <WhyMelbourneHomesNeedProfessionalTermitePestControlPostPage /> },
  { path: 'why-melbourne-homes-need-professional-termite-pest-control/', element: <WhyMelbourneHomesNeedProfessionalTermitePestControlPostPage /> },
  { path: 'why-some-melbourne-homes-never-have-pest-problems', element: <WhySomeMelbourneHomesNeverHavePestProblemsPostPage /> },
  { path: 'why-some-melbourne-homes-never-have-pest-problems/', element: <WhySomeMelbourneHomesNeverHavePestProblemsPostPage /> },
  { path: 'why-your-cafe-restaurant-needs-pest-control-in-melbourne-here-are-5-key-reasons', element: <WhyYourCafeRestaurantNeedsPestControlInMelbourneHereAre5KeyReasonsPostPage /> },
  { path: 'why-your-cafe-restaurant-needs-pest-control-in-melbourne-here-are-5-key-reasons/', element: <WhyYourCafeRestaurantNeedsPestControlInMelbourneHereAre5KeyReasonsPostPage /> },
  { path: 'why-your-diy-traps-arent-working-the-reality-of-rodent-control-in-melbourne', element: <WhyYourDiyTrapsArentWorkingTheRealityOfRodentControlInMelbournePostPage /> },
  { path: 'why-your-diy-traps-arent-working-the-reality-of-rodent-control-in-melbourne/', element: <WhyYourDiyTrapsArentWorkingTheRealityOfRodentControlInMelbournePostPage /> },
  { path: 'why-your-neighbours-rodent-problem-could-be-yours-too', element: <WhyYourNeighboursRodentProblemCouldBeYoursTooPostPage /> },
  { path: 'why-your-neighbours-rodent-problem-could-be-yours-too/', element: <WhyYourNeighboursRodentProblemCouldBeYoursTooPostPage /> },
  { path: 'worried-about-wasp-nests-in-your-office-effective-wasp-control-melbourne-solutions', element: <WorriedAboutWaspNestsInYourOfficeEffectiveWaspControlMelbourneSolutionsPostPage /> },
  { path: 'worried-about-wasp-nests-in-your-office-effective-wasp-control-melbourne-solutions/', element: <WorriedAboutWaspNestsInYourOfficeEffectiveWaspControlMelbourneSolutionsPostPage /> },
]
