// Auto-generated by scripts/convert-commercial.mjs
import OfficePestControlPage from './pages/commercial/OfficePestControlPage.jsx'
import RestaurantCafePestControlPage from './pages/commercial/RestaurantCafePestControlPage.jsx'
import SchoolAndHospitalityFacilityPestControlPage from './pages/commercial/SchoolAndHospitalityFacilityPestControlPage.jsx'
import WarehouseAndFactoryPestControlServicesMelbournePage from './pages/commercial/WarehouseAndFactoryPestControlServicesMelbournePage.jsx'
import MelbournePage from './pages/offices/MelbournePage.jsx'

export const commercialOfficeRoutes = [
  { path: 'office-pest-control', element: <OfficePestControlPage /> },
  { path: 'restaurant-cafe-pest-control', element: <RestaurantCafePestControlPage /> },
  { path: 'school-and-hospitality-facility-pest-control', element: <SchoolAndHospitalityFacilityPestControlPage /> },
  { path: 'warehouse-and-factory-pest-control-services-melbourne', element: <WarehouseAndFactoryPestControlServicesMelbournePage /> },
  { path: 'melbourne', element: <MelbournePage /> },
]
