// Auto-generated by scripts/convert-commercial.mjs
import { Suspense, lazy } from 'react'

const Loading = () => <div style={{ minHeight: 200 }} />
const withSuspense = (node) => <Suspense fallback={<Loading />}>{node}</Suspense>

const CommercialPestControlPageLazy = lazy(() => import('./pages/commercial/CommercialPestControlPage.jsx'))
const OfficePestControlPageLazy = lazy(() => import('./pages/commercial/OfficePestControlPage.jsx'))
const RestaurantCafePestControlPageLazy = lazy(() => import('./pages/commercial/RestaurantCafePestControlPage.jsx'))
const SchoolAndHospitalityFacilityPestControlPageLazy = lazy(() => import('./pages/commercial/SchoolAndHospitalityFacilityPestControlPage.jsx'))
const WarehouseAndFactoryPestControlServicesMelbournePageLazy = lazy(() => import('./pages/commercial/WarehouseAndFactoryPestControlServicesMelbournePage.jsx'))
const MelbournePageLazy = lazy(() => import('./pages/offices/MelbournePage.jsx'))

export const commercialOfficeRoutes = [
  { path: 'commercial-pest-control', element: withSuspense(<CommercialPestControlPageLazy />) },
  { path: 'office-pest-control', element: withSuspense(<OfficePestControlPageLazy />) },
  { path: 'restaurant-cafe-pest-control', element: withSuspense(<RestaurantCafePestControlPageLazy />) },
  { path: 'school-and-hospitality-facility-pest-control', element: withSuspense(<SchoolAndHospitalityFacilityPestControlPageLazy />) },
  { path: 'warehouse-and-factory-pest-control-services-melbourne', element: withSuspense(<WarehouseAndFactoryPestControlServicesMelbournePageLazy />) },
  { path: 'melbourne', element: withSuspense(<MelbournePageLazy />) },
]
