// Auto-generated by scripts/convert-services.mjs
import OurServicesPage from './pages/services/OurServicesPage.jsx'
import SolarPanelBirdProofingPage from './pages/services/SolarPanelBirdProofingPage.jsx'
import OurServicesAntPestControlPage from './pages/services/OurServicesAntPestControlPage.jsx'
import OurServicesBedBugTreatmentPage from './pages/services/OurServicesBedBugTreatmentPage.jsx'
import OurServicesCockroachControlPage from './pages/services/OurServicesCockroachControlPage.jsx'
import OurServicesMosquitoPestControlPage from './pages/services/OurServicesMosquitoPestControlPage.jsx'
import OurServicesFlyControlPage from './pages/services/OurServicesFlyControlPage.jsx'
import OurServicesFoxPestControlInMelbournePage from './pages/services/OurServicesFoxPestControlInMelbournePage.jsx'
import OurServicesMitesControlPage from './pages/services/OurServicesMitesControlPage.jsx'
import OurServicesMothControlPage from './pages/services/OurServicesMothControlPage.jsx'
import OurServicesPossumPestControlPage from './pages/services/OurServicesPossumPestControlPage.jsx'
import RodentControlInMelbournePage from './pages/services/RodentControlInMelbournePage.jsx'
import OurServicesSilverfishTreatmentPage from './pages/services/OurServicesSilverfishTreatmentPage.jsx'
import OurServicesSpiderControlTreatmentPage from './pages/services/OurServicesSpiderControlTreatmentPage.jsx'
import OurServicesTermitePestControlPage from './pages/services/OurServicesTermitePestControlPage.jsx'
import WaspRemovalMelbournePage from './pages/services/WaspRemovalMelbournePage.jsx'
import OurServicesEndOfLeasePestControlPage from './pages/services/OurServicesEndOfLeasePestControlPage.jsx'

export const serviceRoutes = [
  { path: 'our-services', element: <OurServicesPage /> },
  { path: 'solar-panel-bird-proofing', element: <SolarPanelBirdProofingPage /> },
  { path: 'our-services-ant-pest-control', element: <OurServicesAntPestControlPage /> },
  { path: 'our-services-bed-bug-treatment', element: <OurServicesBedBugTreatmentPage /> },
  { path: 'our-services-cockroach-control', element: <OurServicesCockroachControlPage /> },
  { path: 'our-services-mosquito-pest-control', element: <OurServicesMosquitoPestControlPage /> },
  { path: 'our-services-fly-control', element: <OurServicesFlyControlPage /> },
  { path: 'our-services-fox-pest-control-in-melbourne', element: <OurServicesFoxPestControlInMelbournePage /> },
  { path: 'our-services-mites-control', element: <OurServicesMitesControlPage /> },
  { path: 'our-services-moth-control', element: <OurServicesMothControlPage /> },
  { path: 'our-services-possum-pest-control', element: <OurServicesPossumPestControlPage /> },
  { path: 'rodent-control-in-melbourne', element: <RodentControlInMelbournePage /> },
  { path: 'our-services-silverfish-treatment', element: <OurServicesSilverfishTreatmentPage /> },
  { path: 'our-services-spider-control-treatment', element: <OurServicesSpiderControlTreatmentPage /> },
  { path: 'our-services-termite-pest-control', element: <OurServicesTermitePestControlPage /> },
  { path: 'wasp-removal-melbourne', element: <WaspRemovalMelbournePage /> },
  { path: 'our-services-end-of-lease-pest-control', element: <OurServicesEndOfLeasePestControlPage /> },
]
