// Auto-generated by scripts/convert-services.mjs — paths match Yoast sitemap URLs
import { Navigate } from 'react-router-dom'
import OurServicesPage from './pages/services/OurServicesPage.jsx'
import SolarPanelBirdProofingPage from './pages/services/SolarPanelBirdProofingPage.jsx'
import OurServicesAntPestControlPage from './pages/services/OurServicesAntPestControlPage.jsx'
import OurServicesBedBugTreatmentPage from './pages/services/OurServicesBedBugTreatmentPage.jsx'
import OurServicesCockroachControlPage from './pages/services/OurServicesCockroachControlPage.jsx'
import OurServicesMosquitoPestControlPage from './pages/services/OurServicesMosquitoPestControlPage.jsx'
import OurServicesFlyControlPage from './pages/services/OurServicesFlyControlPage.jsx'
import OurServicesFoxPestControlInMelbournePage from './pages/services/OurServicesFoxPestControlInMelbournePage.jsx'
import OurServicesMitesControlPage from './pages/services/OurServicesMitesControlPage.jsx'
import OurServicesMothControlPage from './pages/services/OurServicesMothControlPage.jsx'
import OurServicesPossumPestControlPage from './pages/services/OurServicesPossumPestControlPage.jsx'
import RodentControlInMelbournePage from './pages/services/RodentControlInMelbournePage.jsx'
import OurServicesSilverfishTreatmentPage from './pages/services/OurServicesSilverfishTreatmentPage.jsx'
import OurServicesSpiderControlTreatmentPage from './pages/services/OurServicesSpiderControlTreatmentPage.jsx'
import OurServicesTermitePestControlPage from './pages/services/OurServicesTermitePestControlPage.jsx'
import WaspRemovalMelbournePage from './pages/services/WaspRemovalMelbournePage.jsx'
import OurServicesEndOfLeasePestControlPage from './pages/services/OurServicesEndOfLeasePestControlPage.jsx'

const nestedServiceRoutes = [
  { path: 'our-services', element: <OurServicesPage /> },
  { path: 'our-services/ant-pest-control', element: <OurServicesAntPestControlPage /> },
  { path: 'our-services/bed-bug-treatment', element: <OurServicesBedBugTreatmentPage /> },
  { path: 'our-services/cockroach-control', element: <OurServicesCockroachControlPage /> },
  { path: 'our-services/mosquito-pest-control', element: <OurServicesMosquitoPestControlPage /> },
  { path: 'our-services/fly-control', element: <OurServicesFlyControlPage /> },
  { path: 'our-services/fox-pest-control-in-melbourne', element: <OurServicesFoxPestControlInMelbournePage /> },
  { path: 'our-services/mites-control', element: <OurServicesMitesControlPage /> },
  { path: 'our-services/moth-control', element: <OurServicesMothControlPage /> },
  { path: 'our-services/possum-pest-control', element: <OurServicesPossumPestControlPage /> },
  { path: 'our-services/silverfish-treatment', element: <OurServicesSilverfishTreatmentPage /> },
  { path: 'our-services/spider-control-treatment', element: <OurServicesSpiderControlTreatmentPage /> },
  { path: 'our-services/termite-pest-control', element: <OurServicesTermitePestControlPage /> },
  { path: 'our-services/end-of-lease-pest-control', element: <OurServicesEndOfLeasePestControlPage /> },
  { path: 'solar-panel-bird-proofing', element: <SolarPanelBirdProofingPage /> },
  { path: 'rodent-control-in-melbourne', element: <RodentControlInMelbournePage /> },
  { path: 'wasp-removal-melbourne', element: <WaspRemovalMelbournePage /> },
]

const legacyRedirects = [
  ['our-services-ant-pest-control', '/our-services/ant-pest-control'],
  ['our-services-bed-bug-treatment', '/our-services/bed-bug-treatment'],
  ['our-services-cockroach-control', '/our-services/cockroach-control'],
  ['our-services-mosquito-pest-control', '/our-services/mosquito-pest-control'],
  ['our-services-fly-control', '/our-services/fly-control'],
  ['our-services-fox-pest-control-in-melbourne', '/our-services/fox-pest-control-in-melbourne'],
  ['our-services-mites-control', '/our-services/mites-control'],
  ['our-services-moth-control', '/our-services/moth-control'],
  ['our-services-possum-pest-control', '/our-services/possum-pest-control'],
  ['our-services-silverfish-treatment', '/our-services/silverfish-treatment'],
  ['our-services-spider-control-treatment', '/our-services/spider-control-treatment'],
  ['our-services-termite-pest-control', '/our-services/termite-pest-control'],
  ['our-services-end-of-lease-pest-control', '/our-services/end-of-lease-pest-control'],
  ['flea-treatment', '/our-services/flea-treatment'],
].map(([from, to]) => ({
  path: from,
  element: <Navigate to={to} replace />,
}))

export const serviceRoutes = [...nestedServiceRoutes, ...legacyRedirects]
