// Auto-generated by scripts/convert-services.mjs — paths match Yoast sitemap URLs
import { Suspense, lazy } from 'react'
import { Navigate } from 'react-router-dom'

const Loading = () => <div style={{ minHeight: 200 }} />
const withSuspense = (node) => <Suspense fallback={<Loading />}>{node}</Suspense>

const OurServicesPage = lazy(() => import('./pages/services/OurServicesPage.jsx'))
const SolarPanelBirdProofingPage = lazy(() => import('./pages/services/SolarPanelBirdProofingPage.jsx'))
const OurServicesAntPestControlPage = lazy(() => import('./pages/services/OurServicesAntPestControlPage.jsx'))
const OurServicesBedBugTreatmentPage = lazy(() => import('./pages/services/OurServicesBedBugTreatmentPage.jsx'))
const OurServicesCockroachControlPage = lazy(() => import('./pages/services/OurServicesCockroachControlPage.jsx'))
const OurServicesMosquitoPestControlPage = lazy(() => import('./pages/services/OurServicesMosquitoPestControlPage.jsx'))
const OurServicesFlyControlPage = lazy(() => import('./pages/services/OurServicesFlyControlPage.jsx'))
const OurServicesFoxPestControlInMelbournePage = lazy(() => import('./pages/services/OurServicesFoxPestControlInMelbournePage.jsx'))
const OurServicesMitesControlPage = lazy(() => import('./pages/services/OurServicesMitesControlPage.jsx'))
const OurServicesMothControlPage = lazy(() => import('./pages/services/OurServicesMothControlPage.jsx'))
const OurServicesPossumPestControlPage = lazy(() => import('./pages/services/OurServicesPossumPestControlPage.jsx'))
const RodentControlInMelbournePage = lazy(() => import('./pages/services/RodentControlInMelbournePage.jsx'))
const OurServicesSilverfishTreatmentPage = lazy(() => import('./pages/services/OurServicesSilverfishTreatmentPage.jsx'))
const OurServicesSpiderControlTreatmentPage = lazy(() => import('./pages/services/OurServicesSpiderControlTreatmentPage.jsx'))
const OurServicesTermitePestControlPage = lazy(() => import('./pages/services/OurServicesTermitePestControlPage.jsx'))
const WaspRemovalMelbournePage = lazy(() => import('./pages/services/WaspRemovalMelbournePage.jsx'))
const OurServicesEndOfLeasePestControlPage = lazy(() => import('./pages/services/OurServicesEndOfLeasePestControlPage.jsx'))

const nestedServiceRoutes = [
  { path: 'our-services', element: withSuspense(<OurServicesPage />) },
  { path: 'our-services/ant-pest-control', element: withSuspense(<OurServicesAntPestControlPage />) },
  { path: 'our-services/bed-bug-treatment', element: withSuspense(<OurServicesBedBugTreatmentPage />) },
  { path: 'our-services/cockroach-control', element: withSuspense(<OurServicesCockroachControlPage />) },
  { path: 'our-services/mosquito-pest-control', element: withSuspense(<OurServicesMosquitoPestControlPage />) },
  { path: 'our-services/fly-control', element: withSuspense(<OurServicesFlyControlPage />) },
  { path: 'our-services/fox-pest-control-in-melbourne', element: withSuspense(<OurServicesFoxPestControlInMelbournePage />) },
  { path: 'our-services/mites-control', element: withSuspense(<OurServicesMitesControlPage />) },
  { path: 'our-services/moth-control', element: withSuspense(<OurServicesMothControlPage />) },
  { path: 'our-services/possum-pest-control', element: withSuspense(<OurServicesPossumPestControlPage />) },
  { path: 'our-services/silverfish-treatment', element: withSuspense(<OurServicesSilverfishTreatmentPage />) },
  { path: 'our-services/spider-control-treatment', element: withSuspense(<OurServicesSpiderControlTreatmentPage />) },
  { path: 'our-services/termite-pest-control', element: withSuspense(<OurServicesTermitePestControlPage />) },
  { path: 'our-services/end-of-lease-pest-control', element: withSuspense(<OurServicesEndOfLeasePestControlPage />) },
  { path: 'solar-panel-bird-proofing', element: withSuspense(<SolarPanelBirdProofingPage />) },
  { path: 'rodent-control-in-melbourne', element: withSuspense(<RodentControlInMelbournePage />) },
  { path: 'wasp-removal-melbourne', element: withSuspense(<WaspRemovalMelbournePage />) },
]

const legacyRedirects = [
  ['our-services-ant-pest-control', '/our-services/ant-pest-control'],
  ['our-services-bed-bug-treatment', '/our-services/bed-bug-treatment'],
  ['our-services-cockroach-control', '/our-services/cockroach-control'],
  ['our-services-mosquito-pest-control', '/our-services/mosquito-pest-control'],
  ['our-services-fly-control', '/our-services/fly-control'],
  ['our-services-fox-pest-control-in-melbourne', '/our-services/fox-pest-control-in-melbourne'],
  ['our-services-mites-control', '/our-services/mites-control'],
  ['our-services-moth-control', '/our-services/moth-control'],
  ['our-services-possum-pest-control', '/our-services/possum-pest-control'],
  ['our-services-silverfish-treatment', '/our-services/silverfish-treatment'],
  ['our-services-spider-control-treatment', '/our-services/spider-control-treatment'],
  ['our-services-termite-pest-control', '/our-services/termite-pest-control'],
  ['our-services-end-of-lease-pest-control', '/our-services/end-of-lease-pest-control'],
  ['flea-treatment', '/our-services/flea-treatment'],
].map(([from, to]) => ({
  path: from,
  element: <Navigate to={to} replace />,
}))

export const serviceRoutes = [...nestedServiceRoutes, ...legacyRedirects]
