// Auto-generated by scripts/scrape-and-convert-location.mjs
import { Suspense, lazy } from 'react'

const Loading = () => <div style={{ minHeight: 200 }} />
const withSuspense = (node) => <Suspense fallback={<Loading />}>{node}</Suspense>

const LocationArchivePageLazy = lazy(() => import('./pages/location/LocationArchivePage.jsx'))
const LocationAltonaPageLazy = lazy(() => import('./pages/location/LocationAltonaPage.jsx'))
const LocationArmadalePageLazy = lazy(() => import('./pages/location/LocationArmadalePage.jsx'))
const LocationBeaumarisPageLazy = lazy(() => import('./pages/location/LocationBeaumarisPage.jsx'))
const LocationBentleighPageLazy = lazy(() => import('./pages/location/LocationBentleighPage.jsx'))
const LocationBrightonPageLazy = lazy(() => import('./pages/location/LocationBrightonPage.jsx'))
const LocationBrunswickPageLazy = lazy(() => import('./pages/location/LocationBrunswickPage.jsx'))
const LocationCarltonPageLazy = lazy(() => import('./pages/location/LocationCarltonPage.jsx'))
const LocationCarnegiePageLazy = lazy(() => import('./pages/location/LocationCarnegiePage.jsx'))
const LocationCaufieldPageLazy = lazy(() => import('./pages/location/LocationCaufieldPage.jsx'))
const LocationCheltenhamPageLazy = lazy(() => import('./pages/location/LocationCheltenhamPage.jsx'))
const LocationClaytonPageLazy = lazy(() => import('./pages/location/LocationClaytonPage.jsx'))
const LocationCoburgPageLazy = lazy(() => import('./pages/location/LocationCoburgPage.jsx'))
const LocationCraigieburnPageLazy = lazy(() => import('./pages/location/LocationCraigieburnPage.jsx'))
const LocationCranbournePageLazy = lazy(() => import('./pages/location/LocationCranbournePage.jsx'))
const LocationDandenongPageLazy = lazy(() => import('./pages/location/LocationDandenongPage.jsx'))
const LocationDoreenPageLazy = lazy(() => import('./pages/location/LocationDoreenPage.jsx'))
const LocationElwoodPageLazy = lazy(() => import('./pages/location/LocationElwoodPage.jsx'))
const LocationFerntreeGullyPageLazy = lazy(() => import('./pages/location/LocationFerntreeGullyPage.jsx'))
const LocationFitzroyPageLazy = lazy(() => import('./pages/location/LocationFitzroyPage.jsx'))
const LocationFlemingtonPageLazy = lazy(() => import('./pages/location/LocationFlemingtonPage.jsx'))
const LocationFootscrayPageLazy = lazy(() => import('./pages/location/LocationFootscrayPage.jsx'))
const LocationFrankstonPageLazy = lazy(() => import('./pages/location/LocationFrankstonPage.jsx'))
const LocationGlenroyPageLazy = lazy(() => import('./pages/location/LocationGlenroyPage.jsx'))
const LocationHamptonPageLazy = lazy(() => import('./pages/location/LocationHamptonPage.jsx'))
const LocationHighettPageLazy = lazy(() => import('./pages/location/LocationHighettPage.jsx'))
const LocationKalkalloPageLazy = lazy(() => import('./pages/location/LocationKalkalloPage.jsx'))
const LocationMandurahPageLazy = lazy(() => import('./pages/location/LocationMandurahPage.jsx'))
const LocationMeltonPageLazy = lazy(() => import('./pages/location/LocationMeltonPage.jsx'))
const LocationMerndaPageLazy = lazy(() => import('./pages/location/LocationMerndaPage.jsx'))
const LocationMorningtonPageLazy = lazy(() => import('./pages/location/LocationMorningtonPage.jsx'))
const LocationMountWaverleyPageLazy = lazy(() => import('./pages/location/LocationMountWaverleyPage.jsx'))
const LocationNorthMelbournePageLazy = lazy(() => import('./pages/location/LocationNorthMelbournePage.jsx'))
const LocationPakenhamPageLazy = lazy(() => import('./pages/location/LocationPakenhamPage.jsx'))
const LocationPointCookPageLazy = lazy(() => import('./pages/location/LocationPointCookPage.jsx'))
const LocationPortMelbournePageLazy = lazy(() => import('./pages/location/LocationPortMelbournePage.jsx'))
const LocationRichmondPageLazy = lazy(() => import('./pages/location/LocationRichmondPage.jsx'))
const LocationRingwoodPageLazy = lazy(() => import('./pages/location/LocationRingwoodPage.jsx'))
const LocationSandringhamPageLazy = lazy(() => import('./pages/location/LocationSandringhamPage.jsx'))
const LocationSeafordPageLazy = lazy(() => import('./pages/location/LocationSeafordPage.jsx'))
const LocationSouthMelbournePageLazy = lazy(() => import('./pages/location/LocationSouthMelbournePage.jsx'))
const LocationSouthMorangPageLazy = lazy(() => import('./pages/location/LocationSouthMorangPage.jsx'))
const LocationSouthYaraPageLazy = lazy(() => import('./pages/location/LocationSouthYaraPage.jsx'))
const LocationSpringvalePageLazy = lazy(() => import('./pages/location/LocationSpringvalePage.jsx'))
const LocationStAlbansPageLazy = lazy(() => import('./pages/location/LocationStAlbansPage.jsx'))
const LocationStKildaPageLazy = lazy(() => import('./pages/location/LocationStKildaPage.jsx'))
const LocationSunshinePageLazy = lazy(() => import('./pages/location/LocationSunshinePage.jsx'))
const LocationTarneitPageLazy = lazy(() => import('./pages/location/LocationTarneitPage.jsx'))
const LocationTaylorsLakesPageLazy = lazy(() => import('./pages/location/LocationTaylorsLakesPage.jsx'))
const LocationThomastownPageLazy = lazy(() => import('./pages/location/LocationThomastownPage.jsx'))
const LocationTruganinaPageLazy = lazy(() => import('./pages/location/LocationTruganinaPage.jsx'))
const LocationWerribeePageLazy = lazy(() => import('./pages/location/LocationWerribeePage.jsx'))
const LocationWilliamstownPageLazy = lazy(() => import('./pages/location/LocationWilliamstownPage.jsx'))
const LocationWyndhamValePageLazy = lazy(() => import('./pages/location/LocationWyndhamValePage.jsx'))
const LocationYarravillePageLazy = lazy(() => import('./pages/location/LocationYarravillePage.jsx'))

export const locationRoutes = [
  { path: 'location', element: withSuspense(<LocationArchivePageLazy />) },
  { path: 'location/altona', element: withSuspense(<LocationAltonaPageLazy />) },
  { path: 'location/armadale', element: withSuspense(<LocationArmadalePageLazy />) },
  { path: 'location/beaumaris', element: withSuspense(<LocationBeaumarisPageLazy />) },
  { path: 'location/bentleigh', element: withSuspense(<LocationBentleighPageLazy />) },
  { path: 'location/brighton', element: withSuspense(<LocationBrightonPageLazy />) },
  { path: 'location/brunswick', element: withSuspense(<LocationBrunswickPageLazy />) },
  { path: 'location/carlton', element: withSuspense(<LocationCarltonPageLazy />) },
  { path: 'location/carnegie', element: withSuspense(<LocationCarnegiePageLazy />) },
  { path: 'location/caufield', element: withSuspense(<LocationCaufieldPageLazy />) },
  { path: 'location/cheltenham', element: withSuspense(<LocationCheltenhamPageLazy />) },
  { path: 'location/clayton', element: withSuspense(<LocationClaytonPageLazy />) },
  { path: 'location/coburg', element: withSuspense(<LocationCoburgPageLazy />) },
  { path: 'location/craigieburn', element: withSuspense(<LocationCraigieburnPageLazy />) },
  { path: 'location/cranbourne', element: withSuspense(<LocationCranbournePageLazy />) },
  { path: 'location/dandenong', element: withSuspense(<LocationDandenongPageLazy />) },
  { path: 'location/doreen', element: withSuspense(<LocationDoreenPageLazy />) },
  { path: 'location/elwood', element: withSuspense(<LocationElwoodPageLazy />) },
  { path: 'location/ferntree-gully', element: withSuspense(<LocationFerntreeGullyPageLazy />) },
  { path: 'location/fitzroy', element: withSuspense(<LocationFitzroyPageLazy />) },
  { path: 'location/flemington', element: withSuspense(<LocationFlemingtonPageLazy />) },
  { path: 'location/footscray', element: withSuspense(<LocationFootscrayPageLazy />) },
  { path: 'location/frankston', element: withSuspense(<LocationFrankstonPageLazy />) },
  { path: 'location/glenroy', element: withSuspense(<LocationGlenroyPageLazy />) },
  { path: 'location/hampton', element: withSuspense(<LocationHamptonPageLazy />) },
  { path: 'location/highett', element: withSuspense(<LocationHighettPageLazy />) },
  { path: 'location/kalkallo', element: withSuspense(<LocationKalkalloPageLazy />) },
  { path: 'location/mandurah', element: withSuspense(<LocationMandurahPageLazy />) },
  { path: 'location/melton', element: withSuspense(<LocationMeltonPageLazy />) },
  { path: 'location/mernda', element: withSuspense(<LocationMerndaPageLazy />) },
  { path: 'location/mornington', element: withSuspense(<LocationMorningtonPageLazy />) },
  { path: 'location/mount-waverley', element: withSuspense(<LocationMountWaverleyPageLazy />) },
  { path: 'location/north-melbourne', element: withSuspense(<LocationNorthMelbournePageLazy />) },
  { path: 'location/pakenham', element: withSuspense(<LocationPakenhamPageLazy />) },
  { path: 'location/point-cook', element: withSuspense(<LocationPointCookPageLazy />) },
  { path: 'location/port-melbourne', element: withSuspense(<LocationPortMelbournePageLazy />) },
  { path: 'location/richmond', element: withSuspense(<LocationRichmondPageLazy />) },
  { path: 'location/ringwood', element: withSuspense(<LocationRingwoodPageLazy />) },
  { path: 'location/sandringham', element: withSuspense(<LocationSandringhamPageLazy />) },
  { path: 'location/seaford', element: withSuspense(<LocationSeafordPageLazy />) },
  { path: 'location/south-melbourne', element: withSuspense(<LocationSouthMelbournePageLazy />) },
  { path: 'location/south-morang', element: withSuspense(<LocationSouthMorangPageLazy />) },
  { path: 'location/south-yara', element: withSuspense(<LocationSouthYaraPageLazy />) },
  { path: 'location/springvale', element: withSuspense(<LocationSpringvalePageLazy />) },
  { path: 'location/st-albans', element: withSuspense(<LocationStAlbansPageLazy />) },
  { path: 'location/st-kilda', element: withSuspense(<LocationStKildaPageLazy />) },
  { path: 'location/sunshine', element: withSuspense(<LocationSunshinePageLazy />) },
  { path: 'location/tarneit', element: withSuspense(<LocationTarneitPageLazy />) },
  { path: 'location/taylors-lakes', element: withSuspense(<LocationTaylorsLakesPageLazy />) },
  { path: 'location/thomastown', element: withSuspense(<LocationThomastownPageLazy />) },
  { path: 'location/truganina', element: withSuspense(<LocationTruganinaPageLazy />) },
  { path: 'location/werribee', element: withSuspense(<LocationWerribeePageLazy />) },
  { path: 'location/williamstown', element: withSuspense(<LocationWilliamstownPageLazy />) },
  { path: 'location/wyndham-vale', element: withSuspense(<LocationWyndhamValePageLazy />) },
  { path: 'location/yarraville', element: withSuspense(<LocationYarravillePageLazy />) },
]
